-- ============================================================
-- MIGRATION: Add devices and steps for all labs missing them
-- Safe to run multiple times (uses INSERT ... ON CONFLICT / WHERE NOT EXISTS)
-- ============================================================

-- Helper: only insert device if it doesn't exist for that lab
-- We use a CTE pattern: INSERT WHERE NOT EXISTS

-- ============================================================
-- STP Lab
-- ============================================================
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'SW1', 'switch', 'Cisco 3560', 200, 150, '{"ios":"15.2","ports":24}'
FROM labs l WHERE l.slug = 'stp-loop-prevention' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'SW1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'SW2', 'switch', 'Cisco 3560', 500, 150, '{"ios":"15.2","ports":24}'
FROM labs l WHERE l.slug = 'stp-loop-prevention' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'SW2');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'SW3', 'switch', 'Cisco 2960', 350, 300, '{"ios":"15.2","ports":24}'
FROM labs l WHERE l.slug = 'stp-loop-prevention' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'SW3');

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 1, 'Verify default STP state', E'On **SW1**, check the current spanning-tree status for VLAN 1.', 'show spanning-tree', 'STP elects a root bridge based on the lowest bridge ID (priority + MAC).', 'SW1', ARRAY['show spanning-tree'], 'command', 10
FROM labs l WHERE l.slug = 'stp-loop-prevention' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 2, 'Set SW1 as root bridge', E'Configure **SW1** with priority 4096 to force it as the root bridge for VLAN 1.', 'spanning-tree vlan 1 priority 4096', 'Lower priority = more likely to become root. Default is 32768.', 'SW1', ARRAY['configure terminal', 'spanning-tree vlan 1 priority 4096'], 'command', 15
FROM labs l WHERE l.slug = 'stp-loop-prevention' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 3, 'Enable PortFast on access ports', E'On **SW2**, enable PortFast on interface Gi0/1 to skip the listening/learning states.', 'spanning-tree portfast on the interface', 'PortFast immediately transitions access ports to forwarding, reducing boot time for end devices.', 'SW2', ARRAY['configure terminal', 'interface GigabitEthernet0/1', 'spanning-tree portfast'], 'command', 10
FROM labs l WHERE l.slug = 'stp-loop-prevention' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 4, 'Enable BPDU Guard', E'On **SW2** Gi0/1, enable BPDU Guard to shut down the port if a switch is connected.', 'spanning-tree bpduguard enable', 'BPDU Guard protects PortFast ports by errdisabling them if BPDUs are received.', 'SW2', ARRAY['spanning-tree bpduguard enable'], 'command', 10
FROM labs l WHERE l.slug = 'stp-loop-prevention' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 5, 'Verify STP topology', E'Check the spanning-tree on **SW3** to verify port roles (Root, Designated, Blocking).', 'show spanning-tree', 'Non-root switches have root ports (toward root) and may have blocking ports to prevent loops.', 'SW3', ARRAY['show spanning-tree'], 'command', 10
FROM labs l WHERE l.slug = 'stp-loop-prevention' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 5);

-- ============================================================
-- OSPF Lab
-- ============================================================
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'R1', 'router', 'Cisco ISR 4321', 150, 150, '{"ios":"16.9"}' FROM labs l WHERE l.slug = 'ospf-single-area' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'R2', 'router', 'Cisco ISR 4321', 450, 150, '{"ios":"16.9"}' FROM labs l WHERE l.slug = 'ospf-single-area' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R2');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'R3', 'router', 'Cisco ISR 4321', 300, 300, '{"ios":"16.9"}' FROM labs l WHERE l.slug = 'ospf-single-area' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R3');

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 1, 'Enable OSPF on R1', E'Enter OSPF configuration on **R1** with process ID 1.', 'router ospf 1', 'OSPF process IDs are locally significant — they don''t need to match across routers.', 'R1', ARRAY['configure terminal', 'router ospf 1'], 'command', 10 FROM labs l WHERE l.slug = 'ospf-single-area' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 2, 'Advertise R1 networks', E'Advertise the 10.0.1.0/24 network into OSPF area 0 on **R1**.', 'network 10.0.1.0 0.0.0.255 area 0', 'The network command uses wildcard masks (inverse of subnet mask). Area 0 is the backbone.', 'R1', ARRAY['network 10.0.1.0 0.0.0.255 area 0'], 'command', 10 FROM labs l WHERE l.slug = 'ospf-single-area' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 3, 'Configure OSPF on R2', E'Enable OSPF process 1 on **R2** and advertise 10.0.2.0/24 in area 0.', 'router ospf 1 then network command', 'All routers in the same area exchange LSAs to build an identical LSDB.', 'R2', ARRAY['configure terminal', 'router ospf 1', 'network 10.0.2.0 0.0.0.255 area 0'], 'command', 10 FROM labs l WHERE l.slug = 'ospf-single-area' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 4, 'Configure OSPF on R3', E'Enable OSPF process 1 on **R3** and advertise 10.0.3.0/24 in area 0.', 'Same pattern as R1 and R2', 'Once all routers are in the same area, OSPF calculates the shortest path tree using Dijkstra''s algorithm.', 'R3', ARRAY['configure terminal', 'router ospf 1', 'network 10.0.3.0 0.0.0.255 area 0'], 'command', 10 FROM labs l WHERE l.slug = 'ospf-single-area' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 5, 'Verify OSPF neighbors', E'On **R1**, verify OSPF neighbor adjacencies have formed.', 'show ip ospf neighbor', 'FULL state means adjacency is complete and LSDBs are synchronized.', 'R1', ARRAY['show ip ospf neighbor'], 'command', 10 FROM labs l WHERE l.slug = 'ospf-single-area' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 5);

-- ============================================================
-- LACP Lab
-- ============================================================
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'SW1', 'switch', 'Cisco 3850', 200, 150, '{"ports":48}' FROM labs l WHERE l.slug = 'lacp-etherchannel' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'SW1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'SW2', 'switch', 'Cisco 3850', 500, 150, '{"ports":48}' FROM labs l WHERE l.slug = 'lacp-etherchannel' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'SW2');

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 1, 'Select interfaces for bundling', E'On **SW1**, enter interface range Gi0/1-2 to configure both ports for the EtherChannel.', 'interface range GigabitEthernet0/1-2', 'EtherChannel bundles multiple physical links into one logical link for bandwidth and redundancy.', 'SW1', ARRAY['configure terminal', 'interface range GigabitEthernet0/1-2'], 'command', 10 FROM labs l WHERE l.slug = 'lacp-etherchannel' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 2, 'Configure LACP active mode', E'Set the channel-group to 1 with LACP active mode on **SW1**.', 'channel-group 1 mode active', 'LACP active mode initiates negotiation. Both sides can be active, or one active and one passive.', 'SW1', ARRAY['channel-group 1 mode active'], 'command', 15 FROM labs l WHERE l.slug = 'lacp-etherchannel' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 3, 'Configure SW2 matching LACP', E'On **SW2**, configure the same interface range with channel-group 1 mode active.', 'Same commands as SW1', 'Both ends must be in the same channel-group number and use compatible LACP modes.', 'SW2', ARRAY['configure terminal', 'interface range GigabitEthernet0/1-2', 'channel-group 1 mode active'], 'command', 15 FROM labs l WHERE l.slug = 'lacp-etherchannel' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 4, 'Verify EtherChannel', E'On **SW1**, verify the EtherChannel is up and bundled.', 'show etherchannel summary', 'Look for (P) flags indicating ports are bundled in the port-channel.', 'SW1', ARRAY['show etherchannel summary'], 'command', 10 FROM labs l WHERE l.slug = 'lacp-etherchannel' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

-- ============================================================
-- DHCP Lab
-- ============================================================
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'R1', 'router', 'Cisco ISR 4321', 300, 100, '{"ios":"16.9"}' FROM labs l WHERE l.slug = 'dhcp-server-config' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'PC1', 'workstation', 'Desktop', 300, 300, '{"os":"Linux"}' FROM labs l WHERE l.slug = 'dhcp-server-config' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'PC1');

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 1, 'Exclude reserved addresses', E'On **R1**, exclude addresses 10.0.1.1 through 10.0.1.10 from the DHCP pool.', 'ip dhcp excluded-address 10.0.1.1 10.0.1.10', 'Excluding addresses prevents the DHCP server from assigning IPs reserved for routers, servers, etc.', 'R1', ARRAY['configure terminal', 'ip dhcp excluded-address 10.0.1.1 10.0.1.10'], 'command', 10 FROM labs l WHERE l.slug = 'dhcp-server-config' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 2, 'Create DHCP pool', E'Create a DHCP pool named "LAN" on **R1** with network 10.0.1.0/24.', 'ip dhcp pool LAN → network 10.0.1.0 255.255.255.0', 'Each DHCP pool defines a range of addresses and options to distribute to clients.', 'R1', ARRAY['ip dhcp pool LAN', 'network 10.0.1.0 255.255.255.0'], 'command', 10 FROM labs l WHERE l.slug = 'dhcp-server-config' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 3, 'Set default gateway and DNS', E'In the DHCP pool, set the default router to 10.0.1.1 and DNS server to 8.8.8.8.', 'default-router and dns-server commands', 'DHCP options tell clients which gateway and DNS server to use automatically.', 'R1', ARRAY['default-router 10.0.1.1', 'dns-server 8.8.8.8'], 'command', 10 FROM labs l WHERE l.slug = 'dhcp-server-config' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 4, 'Verify DHCP bindings', E'Check active DHCP leases on **R1**.', 'show ip dhcp binding', 'The binding table shows which IPs have been leased, to which MAC address, and when they expire.', 'R1', ARRAY['show ip dhcp binding'], 'command', 10 FROM labs l WHERE l.slug = 'dhcp-server-config' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

-- ============================================================
-- DNS Lab
-- ============================================================
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'R1', 'router', 'Cisco ISR 4321', 300, 100, '{}' FROM labs l WHERE l.slug = 'dns-resolution' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'DNS-SRV', 'dns_server', 'Linux Server', 300, 300, '{}' FROM labs l WHERE l.slug = 'dns-resolution' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'DNS-SRV');

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 1, 'Enable DNS lookup', E'On **R1**, enable DNS name resolution.', 'ip domain-lookup', 'By default IOS tries to resolve unknown commands as hostnames. This enables explicit DNS.', 'R1', ARRAY['configure terminal', 'ip domain-lookup'], 'command', 10 FROM labs l WHERE l.slug = 'dns-resolution' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 2, 'Set DNS server', E'Point **R1** to the DNS server at 10.0.1.100.', 'ip name-server 10.0.1.100', 'The name-server command tells the router where to send DNS queries.', 'R1', ARRAY['ip name-server 10.0.1.100'], 'command', 10 FROM labs l WHERE l.slug = 'dns-resolution' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 3, 'Set domain name', E'Configure the default domain name as **lab.local** on **R1**.', 'ip domain-name lab.local', 'The domain name is appended to unqualified hostnames for DNS lookups.', 'R1', ARRAY['ip domain-name lab.local'], 'command', 10 FROM labs l WHERE l.slug = 'dns-resolution' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 4, 'Create a static host entry', E'Add a static DNS mapping: **server1** resolves to 10.0.1.100.', 'ip host server1 10.0.1.100', 'Static host entries are resolved locally without querying the DNS server.', 'R1', ARRAY['ip host server1 10.0.1.100'], 'command', 10 FROM labs l WHERE l.slug = 'dns-resolution' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

-- ============================================================
-- BGP Lab
-- ============================================================
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'R1', 'router', 'Cisco ISR 4331', 150, 150, '{"asn":65001}' FROM labs l WHERE l.slug = 'bgp-peering' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'ISP', 'router', 'Cisco ISR 4451', 500, 150, '{"asn":65000}' FROM labs l WHERE l.slug = 'bgp-peering' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'ISP');

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 1, 'Start BGP process', E'On **R1**, start BGP with AS number 65001.', 'router bgp 65001', 'BGP uses AS numbers to identify routing domains. Private ASNs are 64512-65534.', 'R1', ARRAY['configure terminal', 'router bgp 65001'], 'command', 10 FROM labs l WHERE l.slug = 'bgp-peering' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 2, 'Configure eBGP neighbor', E'Add the ISP router (10.0.0.2) as an eBGP neighbor in AS 65000.', 'neighbor 10.0.0.2 remote-as 65000', 'eBGP peers are in different ASes. The remote-as must match the neighbor''s actual AS.', 'R1', ARRAY['neighbor 10.0.0.2 remote-as 65000'], 'command', 15 FROM labs l WHERE l.slug = 'bgp-peering' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 3, 'Advertise a prefix', E'Advertise the 192.168.1.0/24 network into BGP on **R1**.', 'network 192.168.1.0 mask 255.255.255.0', 'The network command in BGP advertises a prefix if it exists in the routing table.', 'R1', ARRAY['network 192.168.1.0 mask 255.255.255.0'], 'command', 10 FROM labs l WHERE l.slug = 'bgp-peering' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 4, 'Verify BGP table', E'Check the BGP routing table on **R1**.', 'show ip bgp', 'The > symbol indicates the best path. * means the route is valid.', 'R1', ARRAY['show ip bgp'], 'command', 10 FROM labs l WHERE l.slug = 'bgp-peering' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

-- ============================================================
-- MPLS Lab
-- ============================================================
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'PE1', 'router', 'Cisco ISR 4331', 150, 150, '{}' FROM labs l WHERE l.slug = 'mpls-label-switching' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'PE1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'P1', 'router', 'Cisco ISR 4451', 400, 150, '{}' FROM labs l WHERE l.slug = 'mpls-label-switching' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'P1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties)
SELECT l.id, 'PE2', 'router', 'Cisco ISR 4331', 650, 150, '{}' FROM labs l WHERE l.slug = 'mpls-label-switching' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'PE2');

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 1, 'Enable MPLS globally', E'On **PE1**, enable MPLS IP on interface Gi0/0.', 'mpls ip under the interface', 'MPLS must be enabled on each interface that participates in label switching.', 'PE1', ARRAY['configure terminal', 'interface GigabitEthernet0/0', 'mpls ip'], 'command', 10 FROM labs l WHERE l.slug = 'mpls-label-switching' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 2, 'Enable MPLS on P1', E'Enable MPLS on both interfaces of **P1** (Gi0/0 and Gi0/1).', 'mpls ip on each interface', 'Core routers (P routers) switch based on labels without examining the IP header.', 'P1', ARRAY['configure terminal', 'interface GigabitEthernet0/0', 'mpls ip', 'interface GigabitEthernet0/1', 'mpls ip'], 'command', 15 FROM labs l WHERE l.slug = 'mpls-label-switching' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points)
SELECT l.id, 3, 'Verify MPLS forwarding table', E'On **PE1**, examine the MPLS forwarding table.', 'show mpls forwarding-table', 'The LFIB shows local labels, outgoing labels, and next-hop interfaces.', 'PE1', ARRAY['show mpls forwarding-table'], 'command', 10 FROM labs l WHERE l.slug = 'mpls-label-switching' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- ============================================================
-- Remaining labs get generic router + 3-4 steps each
-- Pattern: create devices, then steps with NOT EXISTS guards
-- ============================================================

-- Network Tunneling
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R1', 'router', 'Cisco ISR 4331', 200, 150, '{}' FROM labs l WHERE l.slug = 'network-tunneling' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R2', 'router', 'Cisco ISR 4331', 500, 150, '{}' FROM labs l WHERE l.slug = 'network-tunneling' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R2');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Create tunnel interface', E'On **R1**, create a Tunnel0 interface.', 'interface Tunnel0', 'Tunnel interfaces are virtual — they encapsulate packets inside another protocol.', 'R1', ARRAY['configure terminal', 'interface Tunnel0'], 'command', 10 FROM labs l WHERE l.slug = 'network-tunneling' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Set tunnel source and destination', E'Configure the tunnel source as Gi0/0 and destination as 203.0.113.2.', 'tunnel source / tunnel destination', 'The outer header uses these endpoints for delivery across the transport network.', 'R1', ARRAY['tunnel source GigabitEthernet0/0', 'tunnel destination 203.0.113.2'], 'command', 15 FROM labs l WHERE l.slug = 'network-tunneling' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Assign tunnel IP', E'Assign IP 10.255.0.1/30 to the Tunnel0 interface on **R1**.', 'ip address 10.255.0.1 255.255.255.252', 'The tunnel IP is used for routing over the tunnel — separate from the transport IPs.', 'R1', ARRAY['ip address 10.255.0.1 255.255.255.252'], 'command', 10 FROM labs l WHERE l.slug = 'network-tunneling' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- GRE Tunnels (reuse same pattern)
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R1', 'router', 'Cisco ISR 4331', 200, 150, '{}' FROM labs l WHERE l.slug = 'gre-tunnels' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R2', 'router', 'Cisco ISR 4331', 500, 150, '{}' FROM labs l WHERE l.slug = 'gre-tunnels' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R2');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Create GRE tunnel', E'On **R1**, create Tunnel0 and set tunnel mode to GRE.', 'interface Tunnel0 → tunnel mode gre ip', 'GRE is the default tunnel mode on Cisco IOS.', 'R1', ARRAY['configure terminal', 'interface Tunnel0', 'tunnel mode gre ip'], 'command', 10 FROM labs l WHERE l.slug = 'gre-tunnels' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Configure tunnel endpoints', E'Set tunnel source to Gi0/0 and destination to 198.51.100.2 on **R1**.', 'tunnel source/destination', 'GRE adds a 24-byte header (4 GRE + 20 new IP) to each encapsulated packet.', 'R1', ARRAY['tunnel source GigabitEthernet0/0', 'tunnel destination 198.51.100.2'], 'command', 10 FROM labs l WHERE l.slug = 'gre-tunnels' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Verify tunnel status', E'Check the tunnel interface status on **R1**.', 'show interfaces tunnel 0', 'The tunnel should show up/up when both source and destination are reachable.', 'R1', ARRAY['show interfaces tunnel 0'], 'command', 10 FROM labs l WHERE l.slug = 'gre-tunnels' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- Autonomous Systems
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R1', 'router', 'Cisco ISR 4331', 150, 150, '{"asn":65001}' FROM labs l WHERE l.slug = 'autonomous-systems' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R2', 'router', 'Cisco ISR 4331', 450, 150, '{"asn":65001}' FROM labs l WHERE l.slug = 'autonomous-systems' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R2');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'ISP', 'router', 'Cisco ISR 4451', 300, 300, '{"asn":65000}' FROM labs l WHERE l.slug = 'autonomous-systems' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'ISP');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Configure iBGP within AS', E'On **R1**, set up iBGP peering with R2 (both in AS 65001).', 'neighbor R2-IP remote-as 65001', 'iBGP peers share the same AS number. They don''t change the AS path.', 'R1', ARRAY['configure terminal', 'router bgp 65001', 'neighbor 10.0.0.2 remote-as 65001'], 'command', 15 FROM labs l WHERE l.slug = 'autonomous-systems' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Configure eBGP to ISP', E'On **R1**, add eBGP peering with the ISP (AS 65000).', 'neighbor ISP-IP remote-as 65000', 'eBGP peers are in different ASes and prepend their AS to the path.', 'R1', ARRAY['neighbor 10.1.0.1 remote-as 65000'], 'command', 15 FROM labs l WHERE l.slug = 'autonomous-systems' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Verify BGP summary', E'Check BGP neighbor status on **R1**.', 'show ip bgp summary', 'The State/PfxRcd column shows how many prefixes were received from each peer.', 'R1', ARRAY['show ip bgp summary'], 'command', 10 FROM labs l WHERE l.slug = 'autonomous-systems' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- IPv6
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R1', 'router', 'Cisco ISR 4331', 300, 150, '{}' FROM labs l WHERE l.slug = 'ipv6-addressing' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Enable IPv6 routing', E'Enable IPv6 unicast routing on **R1**.', 'ipv6 unicast-routing', 'IPv6 routing is disabled by default on Cisco routers.', 'R1', ARRAY['configure terminal', 'ipv6 unicast-routing'], 'command', 10 FROM labs l WHERE l.slug = 'ipv6-addressing' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Configure IPv6 address', E'Assign 2001:DB8:1::1/64 to Gi0/0 on **R1**.', 'ipv6 address 2001:DB8:1::1/64', 'IPv6 global unicast addresses are the equivalent of IPv4 public addresses.', 'R1', ARRAY['interface GigabitEthernet0/0', 'ipv6 address 2001:DB8:1::1/64'], 'command', 10 FROM labs l WHERE l.slug = 'ipv6-addressing' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Verify IPv6 interfaces', E'Check IPv6 addresses on all interfaces.', 'show ipv6 interface brief', 'Each interface gets a link-local (FE80::) address automatically plus any configured globals.', 'R1', ARRAY['show ipv6 interface brief'], 'command', 10 FROM labs l WHERE l.slug = 'ipv6-addressing' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- Remote Access VPN
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'FW1', 'firewall', 'Cisco ASA 5516', 300, 100, '{}' FROM labs l WHERE l.slug = 'remote-access-vpn' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'FW1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'REMOTE', 'workstation', 'Laptop', 300, 300, '{}' FROM labs l WHERE l.slug = 'remote-access-vpn' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'REMOTE');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Configure ISAKMP policy', E'On **FW1**, create an ISAKMP policy with AES-256 encryption.', 'crypto isakmp policy 10', 'ISAKMP Phase 1 establishes a secure channel for negotiating IPsec parameters.', 'FW1', ARRAY['configure terminal', 'crypto isakmp policy 10', 'encryption aes 256'], 'command', 15 FROM labs l WHERE l.slug = 'remote-access-vpn' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Create transform set', E'Define an IPsec transform set using ESP with AES and SHA.', 'crypto ipsec transform-set', 'Transform sets define the encryption and authentication algorithms for data packets.', 'FW1', ARRAY['crypto ipsec transform-set MYSET esp-aes esp-sha-hmac'], 'command', 15 FROM labs l WHERE l.slug = 'remote-access-vpn' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Verify IPsec SA', E'Check the ISAKMP security associations.', 'show crypto isakmp sa', 'QM_IDLE state means Phase 1 is complete and the tunnel is active.', 'FW1', ARRAY['show crypto isakmp sa'], 'command', 10 FROM labs l WHERE l.slug = 'remote-access-vpn' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- SSH
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R1', 'router', 'Cisco ISR 4321', 300, 150, '{}' FROM labs l WHERE l.slug = 'ssh-secure-mgmt' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Set hostname and domain', E'On **R1**, set hostname and domain name (required for RSA key generation).', 'hostname R1 → ip domain-name lab.local', 'RSA keys use the FQDN (hostname.domain) as part of the key identity.', 'R1', ARRAY['configure terminal', 'hostname R1', 'ip domain-name lab.local'], 'command', 10 FROM labs l WHERE l.slug = 'ssh-secure-mgmt' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Generate RSA keys', E'Generate 2048-bit RSA keys on **R1**.', 'crypto key generate rsa modulus 2048', '2048 bits is the minimum recommended key size for SSH version 2.', 'R1', ARRAY['crypto key generate rsa modulus 2048'], 'command', 10 FROM labs l WHERE l.slug = 'ssh-secure-mgmt' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Restrict VTY to SSH', E'Configure VTY lines 0-4 to accept only SSH connections.', 'transport input ssh under line vty', 'This blocks insecure Telnet access to the management plane.', 'R1', ARRAY['line vty 0 4', 'transport input ssh', 'login local'], 'command', 15 FROM labs l WHERE l.slug = 'ssh-secure-mgmt' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Verify SSH', E'Verify SSH is enabled on **R1**.', 'show ip ssh', 'SSH version 2.0 should be enabled with the configured RSA key size.', 'R1', ARRAY['show ip ssh'], 'command', 10 FROM labs l WHERE l.slug = 'ssh-secure-mgmt' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

-- ACLs
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R1', 'router', 'Cisco ISR 4331', 300, 150, '{}' FROM labs l WHERE l.slug = 'acl-traffic-filtering' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Create named extended ACL', E'On **R1**, create an extended ACL named BLOCK-TELNET.', 'ip access-list extended BLOCK-TELNET', 'Named ACLs are easier to manage than numbered ones — you can edit individual entries.', 'R1', ARRAY['configure terminal', 'ip access-list extended BLOCK-TELNET'], 'command', 10 FROM labs l WHERE l.slug = 'acl-traffic-filtering' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Add deny and permit rules', E'Deny TCP port 23 (Telnet) from any source, then permit all other traffic.', 'deny tcp any any eq 23 → permit ip any any', 'ACLs are processed top-down. The implicit deny at the end blocks everything not explicitly permitted.', 'R1', ARRAY['deny tcp any any eq 23', 'permit ip any any'], 'command', 15 FROM labs l WHERE l.slug = 'acl-traffic-filtering' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Apply ACL to interface', E'Apply BLOCK-TELNET inbound on Gi0/0.', 'ip access-group BLOCK-TELNET in', 'ACLs are applied per-interface, per-direction (in or out).', 'R1', ARRAY['interface GigabitEthernet0/0', 'ip access-group BLOCK-TELNET in'], 'command', 10 FROM labs l WHERE l.slug = 'acl-traffic-filtering' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Verify ACL', E'Check the ACL configuration and hit counts.', 'show access-lists', 'Match counts help you verify the ACL is working and see which rules are being triggered.', 'R1', ARRAY['show access-lists'], 'command', 10 FROM labs l WHERE l.slug = 'acl-traffic-filtering' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

-- NAT
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R1', 'router', 'Cisco ISR 4331', 300, 150, '{}' FROM labs l WHERE l.slug = 'nat-configuration' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Mark inside interface', E'On **R1**, mark Gi0/0 as the NAT inside interface.', 'ip nat inside', 'Inside interfaces face the private network. Outside interfaces face the public network.', 'R1', ARRAY['configure terminal', 'interface GigabitEthernet0/0', 'ip nat inside'], 'command', 10 FROM labs l WHERE l.slug = 'nat-configuration' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Mark outside interface', E'Mark Gi0/1 as the NAT outside interface.', 'ip nat outside', 'NAT translates addresses as packets cross the inside/outside boundary.', 'R1', ARRAY['interface GigabitEthernet0/1', 'ip nat outside'], 'command', 10 FROM labs l WHERE l.slug = 'nat-configuration' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Configure static NAT', E'Create a static NAT mapping: inside 10.0.1.100 to outside 203.0.113.100.', 'ip nat inside source static ...', 'Static NAT creates a permanent one-to-one mapping, useful for servers.', 'R1', ARRAY['ip nat inside source static 10.0.1.100 203.0.113.100'], 'command', 15 FROM labs l WHERE l.slug = 'nat-configuration' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Verify NAT translations', E'Check the NAT translation table.', 'show ip nat translations', 'The translation table shows active mappings between inside local and inside global addresses.', 'R1', ARRAY['show ip nat translations'], 'command', 10 FROM labs l WHERE l.slug = 'nat-configuration' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

-- PAT
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R1', 'router', 'Cisco ISR 4331', 300, 150, '{}' FROM labs l WHERE l.slug = 'pat-overload' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Create ACL for NAT traffic', E'On **R1**, create access-list 1 permitting the 10.0.1.0/24 subnet.', 'access-list 1 permit 10.0.1.0 0.0.0.255', 'The ACL defines which inside addresses are eligible for translation.', 'R1', ARRAY['configure terminal', 'access-list 1 permit 10.0.1.0 0.0.0.255'], 'command', 10 FROM labs l WHERE l.slug = 'pat-overload' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Configure PAT overload', E'Configure PAT using the outside interface with overload.', 'ip nat inside source list 1 interface Gi0/1 overload', 'Overload (PAT) maps many inside hosts to one outside IP using unique port numbers.', 'R1', ARRAY['ip nat inside source list 1 interface GigabitEthernet0/1 overload'], 'command', 15 FROM labs l WHERE l.slug = 'pat-overload' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Verify PAT translations', E'Check the translation table to see port mappings.', 'show ip nat translations', 'PAT entries show different source ports mapped to the same outside IP.', 'R1', ARRAY['show ip nat translations'], 'command', 10 FROM labs l WHERE l.slug = 'pat-overload' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- Wireless AP
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'AP1', 'wireless_ap', 'Cisco Aironet 3800', 300, 150, '{}' FROM labs l WHERE l.slug = 'wireless-ap-config' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'AP1');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Set SSID name', E'Configure the primary SSID as **CorpWiFi** on **AP1**.', 'dot11 ssid CorpWiFi', 'The SSID is the network name that clients see when scanning for wireless networks.', 'AP1', ARRAY['configure terminal', 'dot11 ssid CorpWiFi'], 'command', 10 FROM labs l WHERE l.slug = 'wireless-ap-config' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Set authentication mode', E'Set the SSID authentication to open with WPA2.', 'authentication open / wpa-psk', 'Open authentication with WPA2 means clients authenticate using a pre-shared key.', 'AP1', ARRAY['authentication open', 'authentication key-management wpa version 2'], 'command', 15 FROM labs l WHERE l.slug = 'wireless-ap-config' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Assign VLAN to SSID', E'Map the CorpWiFi SSID to VLAN 10.', 'vlan 10', 'VLAN tagging allows wireless traffic to be segmented just like wired traffic.', 'AP1', ARRAY['vlan 10'], 'command', 10 FROM labs l WHERE l.slug = 'wireless-ap-config' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- Wireless Controller
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'WLC1', 'wireless_controller', 'Cisco 5520 WLC', 300, 100, '{}' FROM labs l WHERE l.slug = 'wireless-controller-mgmt' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'WLC1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'AP1', 'wireless_ap', 'Cisco AP 3800', 300, 300, '{}' FROM labs l WHERE l.slug = 'wireless-controller-mgmt' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'AP1');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Create WLAN on WLC', E'On **WLC1**, create a WLAN named CorpWiFi with ID 1.', 'wlan CorpWiFi 1 CorpWiFi', 'WLANs on a WLC define the SSID, security policy, and interface mapping.', 'WLC1', ARRAY['wlan CorpWiFi 1 CorpWiFi'], 'command', 15 FROM labs l WHERE l.slug = 'wireless-controller-mgmt' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Assign VLAN interface', E'Map the WLAN to the management VLAN interface.', 'interface vlan 10', 'Each WLAN maps to a dynamic interface which carries client traffic on a specific VLAN.', 'WLC1', ARRAY['interface vlan 10'], 'command', 10 FROM labs l WHERE l.slug = 'wireless-controller-mgmt' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Enable the WLAN', E'Enable the WLAN so APs begin broadcasting the SSID.', 'no shutdown', 'WLANs are disabled by default on creation. Enable them to start serving clients.', 'WLC1', ARRAY['no shutdown'], 'command', 10 FROM labs l WHERE l.slug = 'wireless-controller-mgmt' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- Wireless Security
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'WLC1', 'wireless_controller', 'Cisco 5520 WLC', 200, 150, '{}' FROM labs l WHERE l.slug = 'wireless-security-config' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'WLC1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'RADIUS', 'server', 'FreeRADIUS', 500, 150, '{}' FROM labs l WHERE l.slug = 'wireless-security-config' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'RADIUS');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Configure WPA3-Enterprise', E'On **WLC1**, set the WLAN security to WPA3 with 802.1X authentication.', 'security wpa3 → security dot1x', 'WPA3-Enterprise uses 802.1X with a RADIUS server for per-user authentication.', 'WLC1', ARRAY['security wpa3', 'security dot1x'], 'command', 15 FROM labs l WHERE l.slug = 'wireless-security-config' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Add RADIUS server', E'Configure the RADIUS server address (10.0.1.200) and shared secret.', 'radius server → address ipv4 → key', 'The shared secret must match between the WLC and RADIUS server.', 'WLC1', ARRAY['radius server RADIUS-SRV', 'address ipv4 10.0.1.200', 'key radiussecret'], 'command', 15 FROM labs l WHERE l.slug = 'wireless-security-config' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Enable MFP', E'Enable Management Frame Protection to prevent deauthentication attacks.', 'security pmf required', 'PMF (802.11w) protects management frames from spoofing and replay attacks.', 'WLC1', ARRAY['security pmf required'], 'command', 10 FROM labs l WHERE l.slug = 'wireless-security-config' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- Wireless Topology
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'AP1', 'wireless_ap', 'Cisco AP 3800', 150, 200, '{"channel":1}' FROM labs l WHERE l.slug = 'wireless-topology-design' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'AP1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'AP2', 'wireless_ap', 'Cisco AP 3800', 400, 200, '{"channel":6}' FROM labs l WHERE l.slug = 'wireless-topology-design' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'AP2');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'AP3', 'wireless_ap', 'Cisco AP 3800', 275, 350, '{"channel":11}' FROM labs l WHERE l.slug = 'wireless-topology-design' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'AP3');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Set AP1 channel', E'On **AP1**, set the 2.4GHz radio to channel 1.', 'dot11 channel 1', 'Channels 1, 6, and 11 are the only non-overlapping channels in 2.4GHz.', 'AP1', ARRAY['configure terminal', 'interface dot11Radio0', 'channel 1'], 'command', 10 FROM labs l WHERE l.slug = 'wireless-topology-design' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Set AP2 channel', E'On **AP2**, set the 2.4GHz radio to channel 6 to avoid co-channel interference with AP1.', 'channel 6', 'Adjacent APs should use non-overlapping channels to minimize interference.', 'AP2', ARRAY['configure terminal', 'interface dot11Radio0', 'channel 6'], 'command', 10 FROM labs l WHERE l.slug = 'wireless-topology-design' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Set AP3 channel', E'On **AP3**, set channel 11 completing the non-overlapping channel plan.', 'channel 11', 'A proper channel plan with 1/6/11 gives each AP a clean frequency band.', 'AP3', ARRAY['configure terminal', 'interface dot11Radio0', 'channel 11'], 'command', 10 FROM labs l WHERE l.slug = 'wireless-topology-design' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

-- Firewalls
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'FW1', 'firewall', 'Cisco ASA 5516', 300, 150, '{}' FROM labs l WHERE l.slug = 'firewall-zones' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'FW1');
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Create security zones', E'On **FW1**, create INSIDE and OUTSIDE security zones.', 'zone security INSIDE / zone security OUTSIDE', 'Zones group interfaces with similar security requirements.', 'FW1', ARRAY['configure terminal', 'zone security INSIDE', 'zone security OUTSIDE'], 'command', 10 FROM labs l WHERE l.slug = 'firewall-zones' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Create zone pair', E'Create a zone-pair from INSIDE to OUTSIDE.', 'zone-pair security IN-OUT source INSIDE destination OUTSIDE', 'Zone pairs define the direction traffic can flow and which policy applies.', 'FW1', ARRAY['zone-pair security IN-OUT source INSIDE destination OUTSIDE'], 'command', 15 FROM labs l WHERE l.slug = 'firewall-zones' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);
INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Apply inspection policy', E'Create and apply a service-policy that inspects HTTP and HTTPS traffic.', 'service-policy type inspect', 'Stateful inspection tracks connections and allows return traffic automatically.', 'FW1', ARRAY['service-policy type inspect IN-OUT-POLICY'], 'command', 15 FROM labs l WHERE l.slug = 'firewall-zones' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);
