-- ============================================================
-- MIGRATION: Foundation Topics (OSI, Network Types, etc.)
-- 8 new topics + 8 quiz-style labs + theory content
-- ============================================================

-- ── Topics ───────────────────────────────────────────────

INSERT INTO topics (slug, name, description, icon, color, sort_order) VALUES ('osi-model', 'OSI Model', 'Seven layers of network communication', 'layers', '#6366f1', -8) ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, name, description, icon, color, sort_order) VALUES ('network-types', 'Network Types', 'LANs, WANs, MANs and use cases', 'globe', '#0891b2', -7) ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, name, description, icon, color, sort_order) VALUES ('network-topologies', 'Network Topologies', 'Bus, star, ring, mesh designs', 'share-2', '#7c3aed', -6) ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, name, description, icon, color, sort_order) VALUES ('network-devices', 'Types of Devices', 'Hubs, switches, routers, firewalls', 'monitor', '#ea580c', -5) ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, name, description, icon, color, sort_order) VALUES ('cables-transmission', 'Cables & Transmission', 'Copper, fiber, wireless media types', 'cable', '#0d9488', -4) ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, name, description, icon, color, sort_order) VALUES ('routing-fundamentals', 'Routing Fundamentals', 'How routers forward packets', 'route', '#059669', -3) ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, name, description, icon, color, sort_order) VALUES ('how-internet-works', 'How The Internet Works', 'DNS, TCP/IP, routing end-to-end', 'globe', '#2563eb', -2) ON CONFLICT (slug) DO NOTHING;
INSERT INTO topics (slug, name, description, icon, color, sort_order) VALUES ('network-layer-arch', 'Network Layer Architecture', 'TCP/IP model, encapsulation, protocol stacks', 'layers', '#be185d', -1) ON CONFLICT (slug) DO NOTHING;

-- ── Labs ─────────────────────────────────────────────────

INSERT INTO labs (slug, title, subtitle, description, difficulty, estimated_minutes, sort_order) VALUES ('osi-model-quiz', 'OSI Model Quiz', 'Identify the seven layers and their functions', 'Test your understanding of the OSI reference model.', 'beginner', 10, -8) ON CONFLICT (slug) DO NOTHING;
INSERT INTO labs (slug, title, subtitle, description, difficulty, estimated_minutes, sort_order) VALUES ('network-types-quiz', 'Network Types Quiz', 'Classify LANs, WANs, MANs', 'Identify network types and their characteristics.', 'beginner', 10, -7) ON CONFLICT (slug) DO NOTHING;
INSERT INTO labs (slug, title, subtitle, description, difficulty, estimated_minutes, sort_order) VALUES ('network-topologies-quiz', 'Network Topologies Quiz', 'Identify bus, star, ring, mesh designs', 'Match topologies to characteristics.', 'beginner', 10, -6) ON CONFLICT (slug) DO NOTHING;
INSERT INTO labs (slug, title, subtitle, description, difficulty, estimated_minutes, sort_order) VALUES ('network-devices-quiz', 'Network Devices Quiz', 'Match devices to OSI layer and function', 'Identify networking devices and their roles.', 'beginner', 10, -5) ON CONFLICT (slug) DO NOTHING;
INSERT INTO labs (slug, title, subtitle, description, difficulty, estimated_minutes, sort_order) VALUES ('cables-transmission-quiz', 'Cables & Transmission Quiz', 'Match cable types to use cases', 'Identify cable types and transmission characteristics.', 'beginner', 10, -4) ON CONFLICT (slug) DO NOTHING;
INSERT INTO labs (slug, title, subtitle, description, difficulty, estimated_minutes, sort_order) VALUES ('routing-fundamentals-lab', 'Routing Fundamentals', 'Read routing tables and understand forwarding', 'Learn how routers make forwarding decisions.', 'beginner', 15, -3) ON CONFLICT (slug) DO NOTHING;
INSERT INTO labs (slug, title, subtitle, description, difficulty, estimated_minutes, sort_order) VALUES ('how-internet-works-quiz', 'How The Internet Works Quiz', 'Trace a packet from browser to server', 'Understand end-to-end internet communication.', 'beginner', 10, -2) ON CONFLICT (slug) DO NOTHING;
INSERT INTO labs (slug, title, subtitle, description, difficulty, estimated_minutes, sort_order) VALUES ('network-layer-arch-quiz', 'Network Layer Architecture Quiz', 'TCP/IP vs OSI and encapsulation', 'Map models and understand encapsulation.', 'beginner', 10, -1) ON CONFLICT (slug) DO NOTHING;

-- ── Lab-Topic Associations ───────────────────────────────

INSERT INTO lab_topics (lab_id, topic_id) SELECT l.id, t.id FROM labs l, topics t WHERE l.slug = 'osi-model-quiz' AND t.slug = 'osi-model' AND NOT EXISTS (SELECT 1 FROM lab_topics lt WHERE lt.lab_id = l.id AND lt.topic_id = t.id);
INSERT INTO lab_topics (lab_id, topic_id) SELECT l.id, t.id FROM labs l, topics t WHERE l.slug = 'network-types-quiz' AND t.slug = 'network-types' AND NOT EXISTS (SELECT 1 FROM lab_topics lt WHERE lt.lab_id = l.id AND lt.topic_id = t.id);
INSERT INTO lab_topics (lab_id, topic_id) SELECT l.id, t.id FROM labs l, topics t WHERE l.slug = 'network-topologies-quiz' AND t.slug = 'network-topologies' AND NOT EXISTS (SELECT 1 FROM lab_topics lt WHERE lt.lab_id = l.id AND lt.topic_id = t.id);
INSERT INTO lab_topics (lab_id, topic_id) SELECT l.id, t.id FROM labs l, topics t WHERE l.slug = 'network-devices-quiz' AND t.slug = 'network-devices' AND NOT EXISTS (SELECT 1 FROM lab_topics lt WHERE lt.lab_id = l.id AND lt.topic_id = t.id);
INSERT INTO lab_topics (lab_id, topic_id) SELECT l.id, t.id FROM labs l, topics t WHERE l.slug = 'cables-transmission-quiz' AND t.slug = 'cables-transmission' AND NOT EXISTS (SELECT 1 FROM lab_topics lt WHERE lt.lab_id = l.id AND lt.topic_id = t.id);
INSERT INTO lab_topics (lab_id, topic_id) SELECT l.id, t.id FROM labs l, topics t WHERE l.slug = 'routing-fundamentals-lab' AND t.slug = 'routing-fundamentals' AND NOT EXISTS (SELECT 1 FROM lab_topics lt WHERE lt.lab_id = l.id AND lt.topic_id = t.id);
INSERT INTO lab_topics (lab_id, topic_id) SELECT l.id, t.id FROM labs l, topics t WHERE l.slug = 'how-internet-works-quiz' AND t.slug = 'how-internet-works' AND NOT EXISTS (SELECT 1 FROM lab_topics lt WHERE lt.lab_id = l.id AND lt.topic_id = t.id);
INSERT INTO lab_topics (lab_id, topic_id) SELECT l.id, t.id FROM labs l, topics t WHERE l.slug = 'network-layer-arch-quiz' AND t.slug = 'network-layer-arch' AND NOT EXISTS (SELECT 1 FROM lab_topics lt WHERE lt.lab_id = l.id AND lt.topic_id = t.id);

-- ── Devices ──────────────────────────────────────────────

INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'QUIZ', 'server', 'Assessment Terminal', 300, 200, '{}' FROM labs l WHERE l.slug = 'osi-model-quiz' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'QUIZ');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'QUIZ', 'server', 'Assessment Terminal', 300, 200, '{}' FROM labs l WHERE l.slug = 'network-types-quiz' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'QUIZ');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'QUIZ', 'server', 'Assessment Terminal', 300, 200, '{}' FROM labs l WHERE l.slug = 'network-topologies-quiz' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'QUIZ');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'QUIZ', 'server', 'Assessment Terminal', 300, 200, '{}' FROM labs l WHERE l.slug = 'network-devices-quiz' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'QUIZ');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'QUIZ', 'server', 'Assessment Terminal', 300, 200, '{}' FROM labs l WHERE l.slug = 'cables-transmission-quiz' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'QUIZ');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R1', 'router', 'Cisco ISR 4321', 300, 150, '{}' FROM labs l WHERE l.slug = 'routing-fundamentals-lab' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R1');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'R2', 'router', 'Cisco ISR 4321', 500, 150, '{}' FROM labs l WHERE l.slug = 'routing-fundamentals-lab' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'R2');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'QUIZ', 'server', 'Assessment Terminal', 300, 200, '{}' FROM labs l WHERE l.slug = 'how-internet-works-quiz' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'QUIZ');
INSERT INTO devices (lab_id, name, device_type, model, x_pos, y_pos, properties) SELECT l.id, 'QUIZ', 'server', 'Assessment Terminal', 300, 200, '{}' FROM labs l WHERE l.slug = 'network-layer-arch-quiz' AND NOT EXISTS (SELECT 1 FROM devices d WHERE d.lab_id = l.id AND d.name = 'QUIZ');

-- ── Lab Steps ─────────────────────────────────────────────

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Layer 1: Physical', E'What is the name of OSI Layer 1?\n\nThis layer deals with raw bit transmission over physical media.', 'It is the bottom layer', 'Layer 1 (Physical) handles transmission of raw bits. It defines cables, connectors, voltages, and data rates.', 'QUIZ', ARRAY['physical'], 'command', 10 FROM labs l WHERE l.slug = 'osi-model-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Layer 2: Data Link', E'What is the name of OSI Layer 2?\n\nThis layer handles MAC addresses, frame formatting, and error detection.', 'Switches operate at this layer', 'Layer 2 (Data Link) provides node-to-node communication using MAC addresses and Ethernet frames.', 'QUIZ', ARRAY['data link'], 'command', 10 FROM labs l WHERE l.slug = 'osi-model-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Layer 3: Network', E'What is the name of OSI Layer 3?\n\nThis layer handles IP addressing, routing, and packet forwarding.', 'Routers operate at this layer', 'Layer 3 (Network) provides logical addressing (IP) and routing. Key protocols: IP, ICMP, OSPF, BGP.', 'QUIZ', ARRAY['network'], 'command', 10 FROM labs l WHERE l.slug = 'osi-model-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Layer 4: Transport', E'What is the name of OSI Layer 4?\n\nThis layer provides end-to-end communication, port numbers, and reliable (TCP) or fast (UDP) delivery.', 'TCP and UDP operate here', 'Layer 4 (Transport) provides end-to-end communication using port numbers.', 'QUIZ', ARRAY['transport'], 'command', 10 FROM labs l WHERE l.slug = 'osi-model-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 5, 'Which layer does a switch operate at?', E'A switch forwards frames based on MAC addresses.\n\nAt which OSI layer does a switch operate? (type the number)', 'It is Layer 2', 'Switches operate at Layer 2 (Data Link). They learn MAC addresses and build a MAC address table.', 'QUIZ', ARRAY['2'], 'command', 10 FROM labs l WHERE l.slug = 'osi-model-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 5);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 6, 'Which layer does a router operate at?', E'A router forwards packets based on IP addresses.\n\nAt which OSI layer does a router operate? (type the number)', 'It is Layer 3', 'Routers operate at Layer 3 (Network). They consult a routing table to determine the next hop.', 'QUIZ', ARRAY['3'], 'command', 10 FROM labs l WHERE l.slug = 'osi-model-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 6);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Identify: Office Network', E'A network connecting computers within a single office building using Ethernet.\n\nWhat type? (LAN, WAN, or MAN)', 'Covers a small area', 'A LAN covers a building or campus. High-speed (1-100 Gbps), owned by a single organization.', 'QUIZ', ARRAY['lan'], 'command', 10 FROM labs l WHERE l.slug = 'network-types-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Identify: Cross-Country Link', E'A network connecting offices in New York and LA using leased lines.\n\nWhat type? (LAN, WAN, or MAN)', 'Spans a large area', 'A WAN spans large geographic distances using leased lines, MPLS, or VPNs.', 'QUIZ', ARRAY['wan'], 'command', 10 FROM labs l WHERE l.slug = 'network-types-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Identify: City-Wide Network', E'A network connecting multiple buildings across a city using fiber.\n\nWhat type? (LAN, WAN, or MAN)', 'Bigger than LAN, smaller than WAN', 'A MAN covers a city or metro area. Often fiber-based.', 'QUIZ', ARRAY['man'], 'command', 10 FROM labs l WHERE l.slug = 'network-types-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Identify: Home Wi-Fi', E'A small network in your home connecting laptop, phone, TV, and printer.\n\nIs this a LAN or WAN?', 'Single location', 'A home network is a LAN — geographic scope defines it, not the media type.', 'QUIZ', ARRAY['lan'], 'command', 10 FROM labs l WHERE l.slug = 'network-types-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 5, 'Largest WAN', E'What is the largest WAN in the world?', 'You are using it right now', 'The Internet is the largest WAN — a global network of interconnected networks.', 'QUIZ', ARRAY['internet'], 'command', 10 FROM labs l WHERE l.slug = 'network-types-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 5);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Central Device Topology', E'All devices connect to a single central switch. If the switch fails, the network goes down.\n\nWhat topology?', 'Think of a wheel with spokes', 'Star topology — most common LAN design. Simple, easy to troubleshoot.', 'QUIZ', ARRAY['star'], 'command', 10 FROM labs l WHERE l.slug = 'network-topologies-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Every Device Connected', E'Every device has a direct connection to every other device. Very redundant but expensive.\n\nWhat topology?', 'Everything connects to everything', 'Full mesh — maximum redundancy. Needs n(n-1)/2 links.', 'QUIZ', ARRAY['mesh'], 'command', 10 FROM labs l WHERE l.slug = 'network-topologies-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Shared Cable', E'All devices connect to a single shared cable. One break splits the network.\n\nWhat topology?', 'A single long line', 'Bus topology — obsolete for LANs. Used in early Ethernet.', 'QUIZ', ARRAY['bus'], 'command', 10 FROM labs l WHERE l.slug = 'network-topologies-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Token Passing Loop', E'Devices form a closed loop. Data travels in one direction with a token.\n\nWhat topology?', 'Think of a circle', 'Ring topology — Token Ring (802.5) used this. One break stops the entire ring.', 'QUIZ', ARRAY['ring'], 'command', 10 FROM labs l WHERE l.slug = 'network-topologies-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 5, 'Most Common LAN Topology', E'Which topology is used in virtually all modern LANs?', 'Every office uses this', 'Star topology dominates modern LANs with Ethernet switches.', 'QUIZ', ARRAY['star'], 'command', 10 FROM labs l WHERE l.slug = 'network-topologies-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 5);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Layer 2 Forwarding Device', E'This device learns MAC addresses and forwards frames only to the correct port.\n\nWhat device?', 'Operates at Layer 2, builds a MAC table', 'A switch forwards frames based on MAC addresses.', 'QUIZ', ARRAY['switch'], 'command', 10 FROM labs l WHERE l.slug = 'network-devices-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Layer 3 Forwarding Device', E'This device forwards packets between networks based on IP addresses.\n\nWhat device?', 'Consults a routing table', 'A router connects different networks using IP addresses and routing tables.', 'QUIZ', ARRAY['router'], 'command', 10 FROM labs l WHERE l.slug = 'network-devices-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Security Device', E'This device filters traffic between zones using stateful inspection.\n\nWhat device?', 'Between trusted and untrusted networks', 'A firewall controls traffic flow using rules and stateful inspection.', 'QUIZ', ARRAY['firewall'], 'command', 10 FROM labs l WHERE l.slug = 'network-devices-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Obsolete Layer 1 Device', E'This device repeats signals out ALL ports. No intelligence, no MAC table.\n\nWhat device?', 'Just amplifies and repeats', 'A hub operates at Layer 1. Floods every frame — replaced by switches.', 'QUIZ', ARRAY['hub'], 'command', 10 FROM labs l WHERE l.slug = 'network-devices-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 5, 'Wireless Infrastructure Device', E'This device provides Wi-Fi and bridges clients onto the wired LAN.\n\nWhat device? (two words)', 'Broadcasts an SSID', 'An access point bridges wireless clients onto Ethernet using 802.11.', 'QUIZ', ARRAY['access point'], 'command', 10 FROM labs l WHERE l.slug = 'network-devices-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 5);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Common LAN Cable', E'Uses twisted copper pairs and RJ-45 connectors. Categories: Cat5e, Cat6, Cat6a.\n\nWhat cable type? (3 letters)', 'Unshielded twisted pair', 'UTP is the most common LAN cable. Twisting reduces EMI.', 'QUIZ', ARRAY['utp'], 'command', 10 FROM labs l WHERE l.slug = 'cables-transmission-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Long-Distance Cable', E'Uses glass strands to transmit data as light pulses. Immune to EMI. Very high speeds over long distances.\n\nWhat cable type?', 'Uses light not electricity', 'Fiber optic cable — SMF for long distance, MMF for data centers.', 'QUIZ', ARRAY['fiber'], 'command', 10 FROM labs l WHERE l.slug = 'cables-transmission-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Legacy WAN Cable', E'Older cable type connecting routers directly. DB-60 or smart serial connectors. Carries WAN protocols.\n\nWhat cable type?', 'Interface type on older Cisco routers', 'Serial cables carry WAN protocols (HDLC, PPP). Largely replaced by Ethernet WAN.', 'QUIZ', ARRAY['serial'], 'command', 10 FROM labs l WHERE l.slug = 'cables-transmission-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Switch-to-Switch Cable', E'Before Auto-MDI/MDIX, what special cable was needed to connect two switches directly?', 'Swaps TX and RX pairs', 'A crossover cable swaps transmit and receive pairs. Auto-MDI/MDIX eliminated the need.', 'QUIZ', ARRAY['crossover'], 'command', 10 FROM labs l WHERE l.slug = 'cables-transmission-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 5, 'Management Cable', E'Light blue RJ-45 to DB-9/USB cable for initial device configuration via the console port.\n\nWhat is it called?', 'Out-of-band management', 'A console (rollover) cable — 9600 baud, used before any network connectivity exists.', 'QUIZ', ARRAY['console'], 'command', 10 FROM labs l WHERE l.slug = 'cables-transmission-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 5);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Setup: Configure router interfaces', E'On **R1**, assign **10.0.1.1/24** to Gi0/0 and bring it up.', 'ip address then no shutdown', 'Routers need IP addresses on each interface to participate in routing.', 'R1', ARRAY['configure terminal', 'interface GigabitEthernet0/0', 'ip address 10.0.1.1 255.255.255.0', 'no shutdown'], 'command', 10 FROM labs l WHERE l.slug = 'routing-fundamentals-lab' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'View the routing table', E'Examine the routing table to see connected networks.', 'show ip route', 'Connected (C) routes appear automatically when an interface is up with an IP.', 'R1', ARRAY['show ip route'], 'command', 10 FROM labs l WHERE l.slug = 'routing-fundamentals-lab' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Add a static route', E'Add a static route to 10.0.2.0/24 via next-hop 10.0.12.2.', 'ip route 10.0.2.0 255.255.255.0 10.0.12.2', 'Static routes are manual. They tell the router: to reach X, send to Y.', 'R1', ARRAY['ip route 10.0.2.0 255.255.255.0 10.0.12.2'], 'command', 15 FROM labs l WHERE l.slug = 'routing-fundamentals-lab' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Add a default route', E'Add a default route (0.0.0.0/0) pointing to 10.0.12.2.', 'ip route 0.0.0.0 0.0.0.0 10.0.12.2', 'The default route is the catch-all — used when no specific route matches.', 'R1', ARRAY['ip route 0.0.0.0 0.0.0.0 10.0.12.2'], 'command', 15 FROM labs l WHERE l.slug = 'routing-fundamentals-lab' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 5, 'Verify routing table', E'Check the routing table for C (Connected), S (Static), and S* (Default) routes.', 'show ip route', 'Three route types: Connected, Static, and Default. Dynamic protocols add more.', 'R1', ARRAY['show ip route'], 'command', 10 FROM labs l WHERE l.slug = 'routing-fundamentals-lab' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 5);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 6, 'Test connectivity', E'Ping R2 at 10.0.12.2 to verify the link works.', 'ping 10.0.12.2', 'Ping sends ICMP Echo Requests. Success verifies both forward and return paths.', 'R1', ARRAY['ping 10.0.12.2'], 'command', 10 FROM labs l WHERE l.slug = 'routing-fundamentals-lab' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 6);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'Step 1: Name Resolution', E'When you type "google.com", what protocol converts that hostname to an IP? (3 letters)', 'Domain Name ___', 'DNS resolves hostnames to IP addresses via recursive queries.', 'QUIZ', ARRAY['dns'], 'command', 10 FROM labs l WHERE l.slug = 'how-internet-works-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Step 2: Reliable Connection', E'After DNS, your browser uses a three-way handshake for reliable delivery.\n\nWhat protocol? (3 letters)', 'SYN, SYN-ACK, ACK', 'TCP provides reliable, ordered delivery via the three-way handshake.', 'QUIZ', ARRAY['tcp'], 'command', 10 FROM labs l WHERE l.slug = 'how-internet-works-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Step 3: Address Translation', E'Your router changes your private IP to public before sending to the internet.\n\nWhat process? (3 letters)', 'Network Address ___', 'NAT maps private addresses to public addresses at the network boundary.', 'QUIZ', ARRAY['nat'], 'command', 10 FROM labs l WHERE l.slug = 'how-internet-works-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Step 4: Inter-Domain Routing', E'Packets cross multiple ISPs and autonomous systems.\n\nWhat routing protocol? (3 letters)', 'Border Gateway ___', 'BGP is the routing protocol of the internet — exchanges routes between ASes.', 'QUIZ', ARRAY['bgp'], 'command', 10 FROM labs l WHERE l.slug = 'how-internet-works-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 5, 'Step 5: Web Protocol', E'The browser retrieves the page on port 443 with encryption.\n\nWhat protocol? (5 letters)', 'Secure version of HTTP', 'HTTPS uses TLS encryption on port 443 for secure web traffic.', 'QUIZ', ARRAY['https'], 'command', 10 FROM labs l WHERE l.slug = 'how-internet-works-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 5);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 1, 'TCP/IP: Routing Layer', E'The TCP/IP model has 4 layers. Name the one that handles IP addressing and routing. (one word)', 'Equivalent of OSI Layer 3', 'The Internet layer in TCP/IP handles IP addressing, routing, and forwarding.', 'QUIZ', ARRAY['internet'], 'command', 10 FROM labs l WHERE l.slug = 'network-layer-arch-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 1);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 2, 'Encapsulation: Layer 2 Unit', E'When data is encapsulated at Layer 2, what is the unit called? (one word)', 'Ethernet creates these', 'A frame is the Layer 2 PDU — contains MAC addresses, type, payload, and FCS.', 'QUIZ', ARRAY['frame'], 'command', 10 FROM labs l WHERE l.slug = 'network-layer-arch-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 2);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 3, 'Encapsulation: Layer 3 Unit', E'When data is encapsulated at Layer 3, what is the unit called? (one word)', 'IP creates these', 'A packet is the Layer 3 PDU — contains source/destination IP, TTL, and protocol field.', 'QUIZ', ARRAY['packet'], 'command', 10 FROM labs l WHERE l.slug = 'network-layer-arch-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 3);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 4, 'Encapsulation: Layer 4 Unit', E'When data is encapsulated at Layer 4 (TCP), what is the unit called? (one word)', 'TCP creates these', 'A segment is the TCP Layer 4 PDU — contains ports, sequence numbers, flags.', 'QUIZ', ARRAY['segment'], 'command', 10 FROM labs l WHERE l.slug = 'network-layer-arch-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 4);

INSERT INTO lab_steps (lab_id, step_number, title, instruction, hint, explanation, target_device, expected_commands, validation_type, points) SELECT l.id, 5, 'MAC Address Layer', E'At which layer is the destination MAC address added? (type the number)', 'Added in the frame header', 'Layer 2 adds MAC addresses. MACs change at every hop; IPs stay the same end-to-end.', 'QUIZ', ARRAY['2'], 'command', 10 FROM labs l WHERE l.slug = 'network-layer-arch-quiz' AND NOT EXISTS (SELECT 1 FROM lab_steps ls WHERE ls.lab_id = l.id AND ls.step_number = 5);

-- ── Theory Content ────────────────────────────────────────

INSERT INTO topic_content (topic_id, osi_layer, theory_md, practical_md, key_commands, common_mistakes) SELECT t.id, 'All', E'## The OSI Model\n\n7 layers of network communication:\n\n**Layer 7 - Application**: HTTP, FTP, DNS, DHCP\n**Layer 6 - Presentation**: Encryption, compression, encoding\n**Layer 5 - Session**: Session management (NetBIOS, RPC)\n**Layer 4 - Transport**: TCP (reliable) and UDP (fast), port numbers\n**Layer 3 - Network**: IP addressing and routing (routers)\n**Layer 2 - Data Link**: MAC addresses and frames (switches)\n**Layer 1 - Physical**: Cables, connectors, signals (hubs)\n\n### Mnemonic\n**P**lease **D**o **N**ot **T**hrow **S**ausage **P**izza **A**way (1-7)\n\n### Encapsulation\nData -> Segment (L4) -> Packet (L3) -> Frame (L2) -> Bits (L1)', E'## Troubleshooting with OSI\n\nStart from the bottom:\n1. **L1**: Cable plugged in? Link light on?\n2. **L2**: MAC in switch table? STP blocking?\n3. **L3**: Can you ping gateway? Route exists?\n4. **L4**: Port open? Firewall blocking?\n5. **L7**: Service running? DNS resolving?', '[]'::jsonb, '["Confusing OSI (7 layers) with TCP/IP (4 layers)", "Thinking routers are Layer 2"]'::jsonb FROM topics t WHERE t.slug = 'osi-model' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

INSERT INTO topic_content (topic_id, osi_layer, theory_md, practical_md, key_commands, common_mistakes) SELECT t.id, 'All', E'## Network Types\n\n**LAN** (Local Area Network): Building/campus, 1-100 Gbps, Ethernet\n**WAN** (Wide Area Network): Cities/countries, leased lines/MPLS/VPN\n**MAN** (Metropolitan Area Network): City-wide, fiber rings\n**PAN** (Personal Area Network): Bluetooth, few meters\n**WLAN** (Wireless LAN): Wi-Fi-based LAN\n\nThe Internet is the largest WAN.', E'## Identifying Network Types\n\n- Within one building? -> LAN\n- Across a city? -> MAN\n- Crosses state/country lines? -> WAN\n- Wireless in a small area? -> WLAN', '[]'::jsonb, '["Confusing WLAN with WAN", "Thinking WAN always means slow"]'::jsonb FROM topics t WHERE t.slug = 'network-types' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

INSERT INTO topic_content (topic_id, osi_layer, theory_md, practical_md, key_commands, common_mistakes) SELECT t.id, 'Layer 1-2', E'## Network Topologies\n\n**Star**: All devices connect to central switch. Most common.\n**Bus**: All devices on one shared cable. Obsolete.\n**Ring**: Closed loop with token passing. Obsolete.\n**Mesh**: Every device connects to every other. WAN/DC use.\n**Hybrid**: Combination. Most real networks.', E'## Modern Practice\n\n- Access layer: Star (switches to PCs)\n- Distribution: Partial mesh (redundant uplinks)\n- Core/WAN: Full or partial mesh (max uptime)', '[]'::jsonb, '["Thinking bus/ring are still used", "Full mesh does not scale"]'::jsonb FROM topics t WHERE t.slug = 'network-topologies' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

INSERT INTO topic_content (topic_id, osi_layer, theory_md, practical_md, key_commands, common_mistakes) SELECT t.id, 'Layer 1-3', E'## Network Devices\n\n**Hub** (L1): Repeats signals to all ports. No intelligence. Obsolete.\n**Switch** (L2): Learns MACs, forwards frames to correct port only.\n**Router** (L3): Forwards packets between networks using IP addresses.\n**Firewall** (L3-7): Filters traffic using stateful rules.\n**Access Point** (L2): Bridges wireless clients to wired LAN.\n**WLC**: Centrally manages multiple APs.', E'## Hub vs Switch vs Router\n\n| Feature | Hub | Switch | Router |\n|---------|-----|--------|--------|\n| Layer | 1 | 2 | 3 |\n| Addressing | None | MAC | IP |\n| Broadcast domain | 1 | 1/VLAN | 1/interface |', '["show mac address-table", "show ip route"]'::jsonb, '["Thinking hub = switch", "Forgetting L3 switches can route"]'::jsonb FROM topics t WHERE t.slug = 'network-devices' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

INSERT INTO topic_content (topic_id, osi_layer, theory_md, practical_md, key_commands, common_mistakes) SELECT t.id, 'Layer 1', E'## Cables\n\n**UTP**: Twisted copper, RJ-45. Cat5e=1G, Cat6a=10G@100m.\n**Fiber**: Glass/plastic, light pulses. SMF=40+km, MMF=300-550m.\n**Coaxial**: Cable TV/internet (RG-6).\n**Serial**: Legacy WAN (HDLC, PPP).\n\n## Special Cables\n- **Straight-through**: PC to switch\n- **Crossover**: Switch to switch (before Auto-MDI/MDIX)\n- **Console**: Laptop to device console port (9600 baud)', E'## Selection Guide\n\n- Distance > 100m? -> Fiber\n- Speed > 1G? -> Cat6a or fiber\n- EMI environment? -> STP or fiber\n- Budget LAN? -> Cat5e UTP\n- WAN? -> Single-mode fiber', '["show interfaces", "show interfaces status"]'::jsonb, '["Cat6 only does 10G at 55m not 100m", "Confusing SMF and MMF"]'::jsonb FROM topics t WHERE t.slug = 'cables-transmission' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

INSERT INTO topic_content (topic_id, osi_layer, theory_md, practical_md, key_commands, common_mistakes) SELECT t.id, 'Layer 3', E'## Routing\n\nRouters forward packets by looking up destination IP in the routing table.\n\n### Route Types\n- **C** (Connected): From interface IPs. AD=0\n- **S** (Static): Manual config. AD=1\n- **O** (OSPF): Dynamic, link-state. AD=110\n- **B** (BGP): Dynamic, path-vector. AD=20\n- **S*** (Default): Gateway of last resort (0.0.0.0/0)\n\n### Longest Prefix Match\nPacket to 10.0.1.50 matches both 10.0.0.0/8 and 10.0.1.0/24 — the /24 wins.', E'## Key Commands\n\n```\nshow ip route\nip route 10.0.2.0 255.255.255.0 10.0.12.2\nip route 0.0.0.0 0.0.0.0 10.0.12.2\nshow ip interface brief\nping / traceroute\n```', '["show ip route", "ip route", "show ip interface brief", "ping", "traceroute"]'::jsonb, '["Forgetting the default route", "Not understanding longest prefix match"]'::jsonb FROM topics t WHERE t.slug = 'routing-fundamentals' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

INSERT INTO topic_content (topic_id, osi_layer, theory_md, practical_md, key_commands, common_mistakes) SELECT t.id, 'All', E'## How The Internet Works\n\n1. **DNS**: Browser resolves hostname to IP\n2. **TCP**: Three-way handshake (SYN/SYN-ACK/ACK)\n3. **TLS**: Encryption negotiation for HTTPS\n4. **NAT**: Private IP translated to public at router\n5. **Routing**: Packets traverse ISPs via BGP\n6. **Response**: Server sends HTML, TCP ensures delivery\n\n### Key Concept\nMAC addresses change at every hop. IP addresses stay the same end-to-end.', E'## Tracing the Path\n\n```\nYour PC (192.168.1.10)\n  -> DNS query\n  -> TCP handshake\nHome Router (NAT)\n  -> ISP (BGP routing)\n  -> Multiple hops\nDestination Server\n  -> HTTP response\n  -> Reverse path\nYour browser renders\n```', '["traceroute", "ping", "show ip route", "show ip nat translations"]'::jsonb, '["Internet is one network (its thousands of ASes)", "IP addresses change at each hop (only MACs do)"]'::jsonb FROM topics t WHERE t.slug = 'how-internet-works' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

INSERT INTO topic_content (topic_id, osi_layer, theory_md, practical_md, key_commands, common_mistakes) SELECT t.id, 'All', E'## Network Layer Architecture\n\n### TCP/IP Model (4 layers)\n| TCP/IP | OSI Equivalent | Protocols |\n|--------|---------------|-----------|\n| Application | 5,6,7 | HTTP, DNS, SSH |\n| Transport | 4 | TCP, UDP |\n| Internet | 3 | IP, ICMP, ARP |\n| Network Access | 1,2 | Ethernet, Wi-Fi |\n\n### PDU Names\n- L4: Segment (TCP) / Datagram (UDP)\n- L3: Packet\n- L2: Frame\n- L1: Bits\n\n### Key Concept\nIP stays same end-to-end. MAC changes every hop.', E'## Encapsulation in Practice\n\nPC (10.0.1.10) -> Router -> Server (10.0.2.50)\n\n**Hop 1 (PC to Router):**\nSrc MAC: PC | Dst MAC: Router Gi0/0\nSrc IP: 10.0.1.10 | Dst IP: 10.0.2.50\n\n**Hop 2 (Router to Server):**\nSrc MAC: Router Gi0/1 | Dst MAC: Server\nSrc IP: 10.0.1.10 | Dst IP: 10.0.2.50\n\nMACs changed. IPs did not.', '["show ip interface brief", "show interfaces", "show mac address-table"]'::jsonb, '["IP changes at each hop (only MACs)", "Confusing TCP/IP (4) with OSI (7)"]'::jsonb FROM topics t WHERE t.slug = 'network-layer-arch' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);
