-- ============================================================
-- MIGRATION: Theory content for all 22 networking topics
-- Creates topic_content table and seeds comprehensive content
-- Safe to run multiple times
-- ============================================================

CREATE TABLE IF NOT EXISTS topic_content (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    topic_id        UUID NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    osi_layer       VARCHAR(32),
    rfc_references  TEXT[],
    theory_md       TEXT NOT NULL,
    practical_md    TEXT NOT NULL,
    diagram_type    VARCHAR(32) DEFAULT 'topology',
    diagram_data    JSONB DEFAULT '{}',
    key_commands    JSONB DEFAULT '[]',
    common_mistakes JSONB DEFAULT '[]',
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(topic_id)
);

CREATE INDEX IF NOT EXISTS idx_topic_content_topic ON topic_content(topic_id);

-- ============================================================
-- 1. VLANs
-- ============================================================
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 2 — Data Link', ARRAY['IEEE 802.1Q'],
-- THEORY
E'## What Are VLANs?\n\nA **Virtual LAN (VLAN)** is a logical partition of a Layer 2 network. VLANs divide a single physical switch into multiple **isolated broadcast domains**, so devices in different VLANs cannot communicate directly — even if they share the same switch.\n\n## Why VLANs Exist\n\nWithout VLANs, every device on a switch receives every broadcast frame. In a 500-device campus, this means:\n- **Broadcast storms** consume bandwidth\n- **Security** is nonexistent — any device can sniff all traffic\n- **Performance** degrades as the network grows\n\nVLANs solve all three: each VLAN is its own broadcast domain.\n\n## How VLANs Work\n\n### Access Ports\nAn **access port** belongs to exactly one VLAN. The switch strips the VLAN tag from outgoing frames and adds it to incoming frames. End devices (PCs, printers) never see the VLAN tag.\n\n### Trunk Ports\nA **trunk port** carries traffic for multiple VLANs simultaneously using **802.1Q tagging**. Each Ethernet frame gets a 4-byte tag inserted between the source MAC and EtherType fields:\n\n```\n| Dest MAC | Src MAC | 802.1Q Tag (4B) | EtherType | Payload | FCS |\n                     |TPID|PCP|DEI|VID|\n```\n\n- **TPID**: 0x8100 (identifies 802.1Q)\n- **VID**: 12-bit VLAN ID (1–4094)\n- **PCP**: 3-bit priority (for QoS)\n\n### Native VLAN\nThe **native VLAN** is sent untagged on trunk ports. Both sides must agree on the native VLAN — mismatches cause connectivity issues and security vulnerabilities (VLAN hopping).\n\n### VLAN Database\nVLANs are stored locally on each switch. **VTP (VLAN Trunking Protocol)** can synchronize VLAN databases across switches, but many networks disable it to prevent accidental VLAN deletions.\n\n## Inter-VLAN Routing\n\nDevices in different VLANs need a **Layer 3 device** (router or L3 switch) to communicate:\n- **Router-on-a-stick**: A single router interface with sub-interfaces, one per VLAN\n- **SVI (Switch Virtual Interface)**: L3 switches create virtual interfaces per VLAN\n\n## VLAN Ranges\n\n| Range | Use |\n|-------|-----|\n| 1 | Default VLAN (cannot be deleted) |\n| 2–1001 | Normal range (stored in vlan.dat) |\n| 1002–1005 | Legacy (FDDI/Token Ring) |\n| 1006–4094 | Extended range (requires VTP transparent mode) |',

-- PRACTICAL
E'## When to Use VLANs\n\n- **Department segmentation**: Engineering, Sales, HR on separate VLANs\n- **Guest isolation**: Visitors get internet-only VLAN\n- **Voice VLANs**: Separate VLAN for IP phones (QoS priority)\n- **IoT/OT separation**: Keep cameras, sensors off the corporate VLAN\n\n## Essential IOS Commands\n\n```\n! Create a VLAN\nSwitch(config)# vlan 10\nSwitch(config-vlan)# name Engineering\n\n! Assign an access port\nSwitch(config)# interface GigabitEthernet0/1\nSwitch(config-if)# switchport mode access\nSwitch(config-if)# switchport access vlan 10\nSwitch(config-if)# no shutdown\n\n! Configure a trunk port\nSwitch(config)# interface GigabitEthernet0/24\nSwitch(config-if)# switchport trunk encapsulation dot1q\nSwitch(config-if)# switchport mode trunk\nSwitch(config-if)# switchport trunk allowed vlan 10,20,30\n\n! Verify\nSwitch# show vlan brief\nSwitch# show interfaces trunk\nSwitch# show interfaces switchport\n```\n\n## Troubleshooting Checklist\n\n1. Does the VLAN exist on **both** switches? (`show vlan brief`)\n2. Is the trunk link actually trunking? (`show interfaces trunk`)\n3. Is the VLAN **allowed** on the trunk? (`switchport trunk allowed vlan`)\n4. Do both trunk ends agree on **native VLAN**?\n5. Is the port in the right mode? (`show interfaces switchport`)\n\n## Design Best Practices\n\n- Keep VLAN scope to a single distribution layer (avoid stretched VLANs)\n- Use VLAN 1 for nothing — change the native VLAN to an unused ID\n- Document your VLAN numbering scheme (e.g., 10x = floor 1, 20x = floor 2)\n- Prune trunk links to carry only necessary VLANs',

'frame-format',
'{"nodes":[{"id":"pc1","label":"PC1","vlan":10},{"id":"pc2","label":"PC2","vlan":20},{"id":"sw1","label":"SW1"},{"id":"sw2","label":"SW2"},{"id":"pc3","label":"PC3","vlan":10}],"edges":[{"from":"pc1","to":"sw1","label":"access VLAN 10"},{"from":"pc2","to":"sw1","label":"access VLAN 20"},{"from":"sw1","to":"sw2","label":"trunk 802.1Q"},{"from":"pc3","to":"sw2","label":"access VLAN 10"}]}',
'["vlan {id}", "name {name}", "switchport mode access", "switchport access vlan {id}", "switchport mode trunk", "switchport trunk encapsulation dot1q", "switchport trunk allowed vlan {list}", "show vlan brief", "show interfaces trunk"]',
'["Forgetting to create the VLAN on the remote switch", "Native VLAN mismatch between trunk endpoints", "Not allowing the VLAN on the trunk (default allows all, but pruning can block)", "Leaving ports in VLAN 1 (security risk)", "Using VTP server mode and accidentally deleting VLANs network-wide"]'
FROM topics t WHERE t.slug = 'vlans' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- ============================================================
-- 2. STP
-- ============================================================
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 2 — Data Link', ARRAY['IEEE 802.1D', 'IEEE 802.1w (RSTP)'],
E'## What Is Spanning Tree Protocol?\n\n**STP** prevents Layer 2 loops in networks with redundant links. Without STP, frames loop endlessly, broadcast storms overwhelm the network, and MAC address tables become unstable.\n\n## The Problem STP Solves\n\nWhen two switches are connected by multiple paths, a broadcast frame sent by any host gets forwarded out every port (except the one it arrived on). With redundant links, this creates an infinite loop:\n\n1. SW1 sends broadcast → SW2 via link A\n2. SW2 forwards → SW1 via link B\n3. SW1 forwards → SW2 via link A again\n4. **Infinite loop** — frames multiply exponentially\n\n## How STP Works\n\n### Step 1: Root Bridge Election\nAll switches exchange **BPDUs (Bridge Protocol Data Units)**. The switch with the **lowest Bridge ID** becomes the root bridge.\n\n**Bridge ID** = Priority (4 bits) + System ID Extension (12 bits) + MAC Address\n\nDefault priority is **32768**. To force a switch as root, lower its priority.\n\n### Step 2: Port Role Assignment\n- **Root Port**: Best path toward the root bridge (one per non-root switch)\n- **Designated Port**: Best port on each segment toward the root (forwards traffic)\n- **Blocking Port**: Redundant port — does NOT forward traffic\n\n### Step 3: Port States\n\n| State | Duration | Forwards? | Learns MACs? |\n|-------|----------|-----------|-------------|\n| Blocking | — | No | No |\n| Listening | 15 sec | No | No |\n| Learning | 15 sec | No | Yes |\n| Forwarding | — | Yes | Yes |\n| Disabled | — | No | No |\n\nTotal convergence: ~30–50 seconds (802.1D). **RSTP (802.1w)** converges in <1 second.\n\n### RSTP Port Roles\n- **Alternate Port**: Backup path to root (replaces blocking)\n- **Backup Port**: Redundant path on the same segment\n\n## STP Variants\n\n| Variant | Standard | Convergence | Per-VLAN? |\n|---------|----------|-------------|----------|\n| STP | 802.1D | 30-50 sec | No |\n| RSTP | 802.1w | <1 sec | No |\n| PVST+ | Cisco | 30-50 sec | Yes |\n| Rapid-PVST+ | Cisco | <1 sec | Yes |\n| MST | 802.1s | <1 sec | Grouped |',

E'## When STP Matters\n\n- Any network with **redundant uplinks** between switches\n- Access layer to distribution layer connections\n- Data center leaf-spine (though most modern DC fabrics avoid STP entirely)\n\n## Essential Commands\n\n```\n! Set root bridge for a VLAN\nSwitch(config)# spanning-tree vlan 10 priority 4096\n! Or use the macro:\nSwitch(config)# spanning-tree vlan 10 root primary\n\n! Enable PortFast on access ports\nSwitch(config-if)# spanning-tree portfast\n\n! Enable BPDU Guard\nSwitch(config-if)# spanning-tree bpduguard enable\n\n! Global PortFast default\nSwitch(config)# spanning-tree portfast default\n\n! Switch to Rapid-PVST+\nSwitch(config)# spanning-tree mode rapid-pvst\n\n! Verify\nSwitch# show spanning-tree\nSwitch# show spanning-tree vlan 10\nSwitch# show spanning-tree interface Gi0/1\n```\n\n## Design Best Practices\n\n- **Always** designate a root bridge — never leave it to chance\n- Use **Rapid-PVST+** or MST — classic STP is too slow\n- Enable **PortFast** on all access ports (PCs, servers)\n- Enable **BPDU Guard** on PortFast ports to protect against rogue switches\n- Set **Root Guard** on designated ports to prevent unauthorized root bridges\n- Consider **Loop Guard** on root/alternate ports\n\n## Troubleshooting\n\n1. **Unexpected root bridge?** Check `show spanning-tree` — lowest priority wins\n2. **Port stuck in blocking?** Check for BPDU issues or topology changes\n3. **Errdisabled port?** Likely BPDU Guard triggered — check for unauthorized switch\n4. **Slow convergence?** Switch to Rapid-PVST+',

'state-machine',
'{"states":["Blocking","Listening","Learning","Forwarding","Disabled"],"transitions":[{"from":"Blocking","to":"Listening","label":"Selected as RP/DP"},{"from":"Listening","to":"Learning","label":"15 sec"},{"from":"Learning","to":"Forwarding","label":"15 sec"},{"from":"Forwarding","to":"Blocking","label":"Topology change"}]}',
'["spanning-tree vlan {id} priority {val}", "spanning-tree portfast", "spanning-tree bpduguard enable", "spanning-tree mode rapid-pvst", "show spanning-tree", "spanning-tree vlan {id} root primary"]',
'["Not setting a root bridge — random election causes suboptimal paths", "Forgetting PortFast on access ports — 30-second delay for hosts", "Missing BPDU Guard — rogue switch can become root", "Priority math: must be a multiple of 4096", "Mixing STP and RSTP modes across switches"]'
FROM topics t WHERE t.slug = 'stp' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- ============================================================
-- 3. OSPF
-- ============================================================
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3 — Network', ARRAY['RFC 2328 (OSPFv2)', 'RFC 5340 (OSPFv3)'],
E'## What Is OSPF?\n\n**Open Shortest Path First (OSPF)** is a link-state interior gateway protocol (IGP). It builds a complete topological map of the network, then uses **Dijkstra''s algorithm** to calculate the shortest path tree from each router to every destination.\n\n## Why OSPF Over RIP?\n\n| Feature | RIP | OSPF |\n|---------|-----|------|\n| Algorithm | Distance-vector (Bellman-Ford) | Link-state (Dijkstra) |\n| Metric | Hop count (max 15) | Cost (bandwidth-based) |\n| Convergence | Slow (30-sec updates) | Fast (triggered updates) |\n| Scalability | Small networks | Enterprise-scale |\n| VLSM/CIDR | RIPv2 only | Full support |\n\n## OSPF Concepts\n\n### Areas\nOSPF uses **areas** to create hierarchy and reduce LSA flooding:\n- **Area 0 (Backbone)**: All areas must connect to area 0\n- **Stub Areas**: Block external LSAs to reduce LSDB size\n- **NSSA**: Allow limited external routes into stub areas\n\n### LSA Types\n\n| Type | Name | Scope | Purpose |\n|------|------|-------|---------|\n| 1 | Router LSA | Area | Each router''s links |\n| 2 | Network LSA | Area | Multi-access network DR |\n| 3 | Summary LSA | Inter-area | Routes between areas |\n| 4 | ASBR Summary | Inter-area | Path to ASBR |\n| 5 | External LSA | Domain-wide | Routes from other protocols |\n\n### Neighbor States\n\n**Down → Init → 2-Way → ExStart → Exchange → Loading → Full**\n\n- **2-Way**: DR/BDR election happens here\n- **Full**: LSDBs are synchronized — adjacency is complete\n\n### DR/BDR Election\nOn multi-access networks (Ethernet), OSPF elects:\n- **DR (Designated Router)**: Reduces LSA flooding — all routers form adjacency with DR\n- **BDR (Backup DR)**: Takes over if DR fails\n\nElection criteria: highest **priority** (default 1), then highest **router ID**.\n\n### Cost Calculation\n\n```\nCost = Reference Bandwidth / Interface Bandwidth\nDefault reference: 100 Mbps\n\nGigabitEthernet: 100/1000 = 0.1 → rounded to 1\nFastEthernet:    100/100  = 1\nSerial:          100/1.544 = 64\n```',

E'## When to Use OSPF\n\n- **Enterprise campus**: Single-area for small sites, multi-area for large\n- **Data center underlay**: OSPF or IS-IS for spine-leaf fabrics\n- **WAN**: OSPF over tunnels, DMVPN, or MPLS VPNs\n\n## Essential Commands\n\n```\n! Enable OSPF\nRouter(config)# router ospf 1\nRouter(config-router)# router-id 1.1.1.1\nRouter(config-router)# network 10.0.1.0 0.0.0.255 area 0\nRouter(config-router)# network 10.0.2.0 0.0.0.255 area 0\n\n! Set interface cost\nRouter(config-if)# ip ospf cost 10\n\n! Change reference bandwidth\nRouter(config-router)# auto-cost reference-bandwidth 10000\n\n! Passive interface (don''t send hellos)\nRouter(config-router)# passive-interface GigabitEthernet0/2\n\n! Verify\nRouter# show ip ospf neighbor\nRouter# show ip ospf database\nRouter# show ip ospf interface brief\nRouter# show ip route ospf\n```\n\n## Design Best Practices\n\n- Keep **Area 0** as the backbone — all other areas connect to it\n- Use **stub areas** to reduce routing table size at branch sites\n- Set **router-id** explicitly — don''t rely on interface IP selection\n- Use **passive-interface default** then enable OSPF only where needed\n- Adjust **reference bandwidth** to 10G or 100G to differentiate modern links\n- Set **hello/dead timers** consistently across all neighbors\n\n## Troubleshooting\n\n1. **Neighbors stuck in INIT?** Check hello/dead timer mismatch, area mismatch, or ACLs blocking OSPF (protocol 89)\n2. **Stuck in EXSTART?** MTU mismatch — both sides must agree\n3. **Missing routes?** Check area configuration and network statements\n4. **Suboptimal path?** Verify costs with `show ip ospf interface`',

'area-hierarchy',
'{"areas":[{"id":0,"label":"Area 0 (Backbone)","routers":["R1","R2","ABR1"]},{"id":1,"label":"Area 1","routers":["ABR1","R3","R4"]},{"id":2,"label":"Area 2 (Stub)","routers":["ABR2","R5"]}]}',
'["router ospf {pid}", "network {ip} {wildcard} area {id}", "show ip ospf neighbor", "show ip ospf database", "router-id {ip}", "passive-interface {if}", "ip ospf cost {val}"]',
'["Mismatched hello/dead timers between neighbors", "Forgetting that wildcard masks are inverted subnet masks", "MTU mismatch preventing Full state", "Not all areas connecting to Area 0", "Leaving reference bandwidth at 100 Mbps (all GigE links show cost 1)"]'
FROM topics t WHERE t.slug = 'ospf' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- ============================================================
-- 4. LACP
-- ============================================================
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 2 — Data Link', ARRAY['IEEE 802.3ad', 'IEEE 802.1AX'],
E'## What Is LACP?\n\n**Link Aggregation Control Protocol (LACP)** bundles multiple physical Ethernet links into a single logical **port-channel** (EtherChannel on Cisco). This provides:\n\n- **Increased bandwidth**: 2× GigE = 2 Gbps logical link\n- **Redundancy**: If one link fails, traffic continues on the remaining links\n- **Load balancing**: Traffic is distributed across member links\n\n## How LACP Works\n\nLACP peers exchange **LACPDUs** (LACP Data Units) every 30 seconds (slow) or 1 second (fast) to:\n1. Discover which ports should be bundled\n2. Negotiate channel formation\n3. Detect link failures\n\n### Modes\n\n| Mode | Behavior |\n|------|----------|\n| **Active** | Initiates LACP negotiation |\n| **Passive** | Responds to LACP but doesn''t initiate |\n\nAt least one side must be **active**. Both sides active works fine.\n\n### PAgP (Cisco proprietary alternative)\n\n| Mode | Behavior |\n|------|----------|\n| **Desirable** | Initiates PAgP |\n| **Auto** | Responds only |\n\n## Load Balancing\n\nThe switch hashes traffic across member links using configurable criteria:\n- **src-mac**: Source MAC address\n- **dst-mac**: Destination MAC\n- **src-dst-mac**: Both MACs (most common L2)\n- **src-dst-ip**: Source + destination IP (best for L3)\n\n## Requirements for Bundling\n\nAll member ports must match:\n- Speed and duplex\n- VLAN configuration (access VLAN or trunk settings)\n- STP settings\n- MTU',

E'## When to Use LACP\n\n- **Switch-to-switch uplinks**: Double or triple bandwidth between distribution and access layers\n- **Server NIC teaming**: Bond multiple server NICs to a switch port-channel\n- **Firewall HA**: High-throughput firewall connections\n\n## Essential Commands\n\n```\n! Configure LACP on member interfaces\nSwitch(config)# interface range GigabitEthernet0/1-2\nSwitch(config-if-range)# channel-group 1 mode active\nSwitch(config-if-range)# no shutdown\n\n! Configure the port-channel interface\nSwitch(config)# interface Port-channel1\nSwitch(config-if)# switchport mode trunk\n\n! Set load balancing method\nSwitch(config)# port-channel load-balance src-dst-ip\n\n! Verify\nSwitch# show etherchannel summary\nSwitch# show etherchannel port-channel\nSwitch# show lacp neighbor\nSwitch# show lacp counters\n```\n\n## Troubleshooting\n\n1. **Channel not forming?** Check that speed, duplex, VLAN, and STP match on all member ports\n2. **Suspended ports?** One side may be misconfigured — check `show etherchannel summary` for (s) flags\n3. **Uneven traffic distribution?** Change the load-balance hash algorithm\n4. **Individual (I) state?** Port is configured but not bundled — check LACP mode compatibility',

'bundle',
'{"links":[{"from":"SW1-Gi0/1","to":"SW2-Gi0/1"},{"from":"SW1-Gi0/2","to":"SW2-Gi0/2"}],"channel":"Po1","bandwidth":"2 Gbps"}',
'["channel-group {id} mode active", "channel-group {id} mode passive", "show etherchannel summary", "show lacp neighbor", "port-channel load-balance {method}", "interface Port-channel{id}"]',
'["Mismatched speed/duplex on member ports", "Configuring the port-channel interface before the member ports", "Mixing LACP and PAgP modes", "Not matching trunk/access settings across all members", "Exceeding 8 active members per channel (Cisco limit)"]'
FROM topics t WHERE t.slug = 'lacp' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- ============================================================
-- 5–22: Remaining topics (condensed inserts)
-- ============================================================

-- 5. DHCP
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 7 — Application', ARRAY['RFC 2131'],
E'## What Is DHCP?\n\n**Dynamic Host Configuration Protocol** automatically assigns IP addresses, subnet masks, default gateways, and DNS servers to network clients. Without DHCP, every device would need manual IP configuration.\n\n## DORA Process\n\nDHCP uses a 4-step handshake:\n\n1. **Discover**: Client broadcasts "I need an IP" (UDP 67/68)\n2. **Offer**: Server responds with an available IP\n3. **Request**: Client formally requests the offered IP\n4. **Acknowledge**: Server confirms the lease\n\n## Key Concepts\n\n- **Lease Time**: How long the client keeps the IP (default varies, typically 24h)\n- **Scope/Pool**: Range of IPs the server can assign\n- **Exclusions**: IPs reserved for static devices (routers, servers)\n- **DHCP Relay (ip helper-address)**: Forwards broadcasts across subnets to a central DHCP server\n- **Options**: Extra parameters (Option 150 = TFTP for IP phones, Option 43 = WLC IP for lightweight APs)',
E'## Essential Commands\n\n```\n! Create DHCP pool\nRouter(config)# ip dhcp pool OFFICE\nRouter(dhcp-config)# network 10.0.1.0 255.255.255.0\nRouter(dhcp-config)# default-router 10.0.1.1\nRouter(dhcp-config)# dns-server 8.8.8.8 8.8.4.4\nRouter(dhcp-config)# lease 1\n\n! Exclude addresses\nRouter(config)# ip dhcp excluded-address 10.0.1.1 10.0.1.20\n\n! DHCP relay on remote subnet\nRouter(config-if)# ip helper-address 10.0.0.5\n\n! Verify\nRouter# show ip dhcp binding\nRouter# show ip dhcp pool\nRouter# show ip dhcp conflict\n```\n\n## Troubleshooting\n\n1. **No IP assigned?** Check DHCP pool exists and isn''t exhausted\n2. **Wrong gateway?** Verify default-router in the pool\n3. **Remote subnet not working?** Missing ip helper-address on the gateway interface',
'dora-sequence', '{}',
'["ip dhcp pool {name}", "network {ip} {mask}", "default-router {ip}", "dns-server {ip}", "ip dhcp excluded-address {start} {end}", "ip helper-address {ip}", "show ip dhcp binding"]',
'["Forgetting to exclude the router gateway IP from the pool", "Missing ip helper-address for remote subnets", "Pool network not matching the interface subnet", "DHCP snooping blocking legitimate DHCP on access switches"]'
FROM topics t WHERE t.slug = 'dhcp' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 6. DNS
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 7 — Application', ARRAY['RFC 1034', 'RFC 1035'],
E'## What Is DNS?\n\n**Domain Name System** translates human-readable hostnames (www.example.com) into IP addresses (93.184.216.34). DNS is hierarchical and distributed.\n\n## DNS Hierarchy\n\n```\n. (root)\n├── .com\n│   ├── example.com\n│   └── google.com\n├── .org\n└── .net\n```\n\n## Record Types\n\n| Type | Purpose | Example |\n|------|---------|--------|\n| A | IPv4 address | www → 10.0.1.5 |\n| AAAA | IPv6 address | www → 2001:db8::1 |\n| CNAME | Alias | mail → server1 |\n| MX | Mail server | @ → mail.example.com |\n| PTR | Reverse lookup | 10.0.1.5 → www |\n| NS | Nameserver | @ → ns1.example.com |\n| SOA | Zone authority | Serial, refresh, retry |\n\n## Resolution Process\n\n1. Client checks **local cache**\n2. Queries configured **DNS server** (recursive resolver)\n3. Resolver queries **root servers** → TLD servers → **authoritative server**\n4. Answer cached at each level per TTL',
E'## Router DNS Commands\n\n```\n! Enable DNS lookup\nRouter(config)# ip domain-lookup\n\n! Set DNS server\nRouter(config)# ip name-server 8.8.8.8\n\n! Set domain name\nRouter(config)# ip domain-name lab.local\n\n! Static host entry\nRouter(config)# ip host server1 10.0.1.100\n\n! Verify\nRouter# show hosts\n```\n\n## Troubleshooting\n\n- `nslookup` or `dig` to test resolution\n- Check if DNS server is reachable (`ping`)\n- Verify `ip name-server` is configured\n- Check for DNS traffic filtering (UDP/TCP port 53)',
'hierarchy', '{}',
'["ip domain-lookup", "ip name-server {ip}", "ip domain-name {name}", "ip host {name} {ip}", "show hosts"]',
'["Forgetting ip domain-lookup", "DNS server unreachable due to missing route", "IOS resolving mistyped commands as hostnames (annoying delay)"]'
FROM topics t WHERE t.slug = 'dns' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 7. BGP
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3 — Network', ARRAY['RFC 4271'],
E'## What Is BGP?\n\n**Border Gateway Protocol** is the routing protocol of the internet. BGP is a **path-vector** protocol that exchanges routing information between **autonomous systems (ASes)**. Every ISP, cloud provider, and large enterprise uses BGP.\n\n## eBGP vs iBGP\n\n| Feature | eBGP | iBGP |\n|---------|------|------|\n| Between | Different ASes | Same AS |\n| TTL | 1 (neighbors must be adjacent) | 255 |\n| Next-hop | Changes | Preserved |\n| AS-path | Prepends local AS | No change |\n| Full mesh | No | Required (or use route reflectors) |\n\n## Path Selection (Decision Process)\n\nBGP selects the best path using these criteria **in order**:\n\n1. Highest **Weight** (Cisco-only, local)\n2. Highest **Local Preference** (within AS)\n3. **Locally originated** route preferred\n4. Shortest **AS-Path**\n5. Lowest **Origin** (IGP < EGP < incomplete)\n6. Lowest **MED** (Multi-Exit Discriminator)\n7. **eBGP** over iBGP\n8. Lowest **IGP metric** to next-hop\n9. Oldest route\n10. Lowest **Router ID**\n\n## BGP Message Types\n\n- **OPEN**: Establish session (AS number, router ID, capabilities)\n- **UPDATE**: Advertise/withdraw routes\n- **KEEPALIVE**: Maintain session (every 60 sec)\n- **NOTIFICATION**: Error — session teardown',
E'## Essential Commands\n\n```\n! Start BGP\nRouter(config)# router bgp 65001\nRouter(config-router)# bgp router-id 1.1.1.1\n\n! eBGP neighbor\nRouter(config-router)# neighbor 10.0.0.2 remote-as 65000\n\n! iBGP neighbor\nRouter(config-router)# neighbor 10.1.1.2 remote-as 65001\nRouter(config-router)# neighbor 10.1.1.2 update-source Loopback0\n\n! Advertise prefix\nRouter(config-router)# network 192.168.1.0 mask 255.255.255.0\n\n! Route map for path manipulation\nRouter(config)# route-map SET-LP permit 10\nRouter(config-route-map)# set local-preference 200\n\n! Verify\nRouter# show ip bgp\nRouter# show ip bgp summary\nRouter# show ip bgp neighbors\n```\n\n## Troubleshooting\n\n1. **Session stuck in Active?** Check reachability, AS number, and ACLs\n2. **Route not in table?** Verify the prefix exists in the RIB (BGP network command requires exact match)\n3. **Suboptimal path?** Check local-pref, AS-path, and weight',
'as-topology', '{}',
'["router bgp {asn}", "neighbor {ip} remote-as {asn}", "network {prefix} mask {mask}", "show ip bgp", "show ip bgp summary", "show ip bgp neighbors"]',
'["BGP network command requires an exact match in the routing table", "iBGP requires full mesh or route reflectors", "Forgetting update-source for iBGP over loopbacks", "eBGP peers must be directly connected (or use ebgp-multihop)"]'
FROM topics t WHERE t.slug = 'bgp' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 8. MPLS
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 2.5', ARRAY['RFC 3031', 'RFC 3032'],
E'## What Is MPLS?\n\n**Multiprotocol Label Switching** forwards packets based on short **labels** instead of long IP addresses. Labels are inserted between the L2 and L3 headers — sometimes called "Layer 2.5".\n\n## Why MPLS?\n\n- **Speed**: Label lookup is simpler than longest-prefix IP lookup (historically significant, less so today)\n- **Traffic Engineering**: Path traffic along specific routes\n- **VPN Services**: L3VPN (RFC 4364) and L2VPN for customers\n- **QoS**: EXP bits in the label for priority marking\n\n## MPLS Label Format (4 bytes)\n\n```\n| Label (20 bits) | EXP (3) | S (1) | TTL (8) |\n```\n\n- **Label**: 0–1,048,575 (0–15 reserved)\n- **EXP**: QoS/Traffic class\n- **S**: Bottom-of-stack (1 = last label)\n- **TTL**: Same as IP TTL\n\n## Key Operations\n\n| Operation | Where | Action |\n|-----------|-------|--------|\n| **Push** | Ingress PE | Add label to packet |\n| **Swap** | Core P | Replace label |\n| **Pop** | Egress PE | Remove label |\n| **PHP** | Penultimate hop | Pop label before egress (optimization) |',
E'## Essential Commands\n\n```\n! Enable MPLS on an interface\nRouter(config-if)# mpls ip\n\n! Verify labels\nRouter# show mpls forwarding-table\nRouter# show mpls ldp neighbor\nRouter# show mpls ldp bindings\nRouter# show mpls interfaces\n```\n\n## Troubleshooting\n\n- **No label for prefix?** Check LDP sessions and IGP reachability\n- **Packet drops at PE?** Verify VRF configuration\n- **PHP not working?** Check implicit-null label assignment',
'label-path', '{}',
'["mpls ip", "show mpls forwarding-table", "show mpls ldp neighbor", "show mpls ldp bindings"]',
'["Forgetting to enable MPLS on all core-facing interfaces", "LDP router-id mismatch", "IGP not converged before MPLS labels assigned"]'
FROM topics t WHERE t.slug = 'mpls' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 9. Network Tunneling
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3 — Network', ARRAY['RFC 2784 (GRE)', 'RFC 4301 (IPsec)'],
E'## What Is Network Tunneling?\n\nTunneling **encapsulates** one protocol inside another, creating a virtual point-to-point link across an intermediate network. The original packet becomes the payload of a new outer packet.\n\n## Common Tunnel Types\n\n| Protocol | Encrypts? | Multicast? | Overhead | Use Case |\n|----------|-----------|------------|----------|---------|\n| GRE | No | Yes | 24 bytes | Routing over internet |\n| IPsec | Yes | No (ESP) | 50-70 bytes | Secure site-to-site |\n| GRE+IPsec | Yes | Yes | 74+ bytes | Secure + multicast |\n| VXLAN | No | Yes | 50 bytes | Data center overlay |\n| L2TP | Optional | No | Variable | Remote access VPN |\n\n## Encapsulation\n\n```\nOriginal:  [IP Header] [Payload]\nTunneled:  [New IP Header] [GRE/ESP Header] [Original IP Header] [Payload]\n```\n\nThe **outer IP header** has the tunnel source/destination. The **inner IP header** is the original packet, preserved intact.',
E'## Essential Commands\n\n```\n! GRE tunnel\nRouter(config)# interface Tunnel0\nRouter(config-if)# ip address 10.255.0.1 255.255.255.252\nRouter(config-if)# tunnel source GigabitEthernet0/0\nRouter(config-if)# tunnel destination 203.0.113.2\nRouter(config-if)# tunnel mode gre ip\n\n! Verify\nRouter# show interfaces tunnel 0\nRouter# show ip route\n```\n\n## Key Considerations\n\n- **MTU**: Tunneling adds overhead — reduce MTU or enable fragmentation\n- **Recursive routing**: Don''t route tunnel destination through the tunnel itself\n- **Keepalives**: GRE supports keepalives to detect remote endpoint failure',
'encapsulation', '{}',
'["interface Tunnel{id}", "tunnel source {if}", "tunnel destination {ip}", "tunnel mode gre ip", "show interfaces tunnel {id}"]',
'["Recursive routing: tunnel destination learned via the tunnel itself", "MTU issues causing fragmentation and black holes", "Forgetting to route the tunnel destination via a non-tunnel path"]'
FROM topics t WHERE t.slug = 'tunneling' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 10. GRE
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3 — Network', ARRAY['RFC 2784', 'RFC 2890'],
E'## What Is GRE?\n\n**Generic Routing Encapsulation** is a simple tunneling protocol that can encapsulate virtually any network-layer protocol. GRE tunnels are commonly used to:\n\n- Run **OSPF, EIGRP, or multicast** over the internet (IPsec alone can''t carry multicast)\n- Connect non-contiguous private networks\n- Create overlay networks\n\n## GRE Header\n\n```\n| C | R | K | S | s | Recur | Flags | Version | Protocol Type |\n| Checksum (optional)  | Offset (optional)   |\n| Key (optional)       |\n| Sequence (optional)  |\n```\n\nMinimum GRE overhead: **4 bytes** (plus 20 bytes for the new IP header = 24 total).\n\n## GRE vs IPsec\n\n| Feature | GRE | IPsec | GRE over IPsec |\n|---------|-----|-------|---------------|\n| Encryption | No | Yes | Yes |\n| Multicast | Yes | No | Yes |\n| Overhead | 24B | 50-70B | 74+B |\n| Routing protocols | Yes | No | Yes |',
E'## Essential Commands\n\n```\n! Create GRE tunnel\nRouter(config)# interface Tunnel0\nRouter(config-if)# ip address 10.255.0.1 255.255.255.252\nRouter(config-if)# tunnel source GigabitEthernet0/0\nRouter(config-if)# tunnel destination 198.51.100.2\nRouter(config-if)# no shutdown\n\n! Run OSPF over GRE\nRouter(config)# router ospf 1\nRouter(config-router)# network 10.255.0.0 0.0.0.3 area 0\n\n! Verify\nRouter# show interfaces tunnel 0\nRouter# ping 10.255.0.2\n```',
'tunnel', '{}',
'["interface Tunnel{id}", "tunnel source {if/ip}", "tunnel destination {ip}", "tunnel mode gre ip", "show interfaces tunnel {id}"]',
'["Forgetting no shutdown on the tunnel interface", "Recursive routing loop", "Not adjusting MTU/MSS for tunnel overhead"]'
FROM topics t WHERE t.slug = 'gre' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 11-22: Remaining topics (shorter format)
-- 11. Autonomous Systems
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3 — Network', ARRAY['RFC 1930', 'RFC 6996'],
E'## What Is an Autonomous System?\n\nAn **AS** is a collection of IP networks under a single administrative domain that presents a common routing policy to the internet. Each AS is identified by a unique **ASN (AS Number)**.\n\n## ASN Ranges\n\n| Range | Type |\n|-------|------|\n| 1–64495 | Public (IANA assigned) |\n| 64512–65534 | Private (16-bit) |\n| 4200000000–4294967294 | Private (32-bit) |\n\n## Internet Structure\n\n- **Tier 1**: Global transit providers (peer freely, no upstream)\n- **Tier 2**: Regional ISPs (buy transit from Tier 1, peer with each other)\n- **Tier 3**: Local ISPs (buy transit from Tier 2)\n- **Enterprises**: Single or multi-homed to ISPs\n\n## Peering Types\n\n- **Transit**: Pay upstream for full internet routing table\n- **Peering**: Exchange traffic directly (settlement-free or paid) at IXPs\n- **Customer**: Your downstream pays you for connectivity',
E'## Practical Considerations\n\n- Most enterprises use **private ASNs** with their ISP\n- Multi-homed enterprises need a **public ASN** and **provider-independent IP space**\n- Configure iBGP within your AS, eBGP to peers/providers\n\n## Commands\n\n```\nRouter(config)# router bgp 65001\nRouter(config-router)# neighbor 10.0.0.1 remote-as 65000\nRouter# show ip bgp summary\n```',
'internet-hierarchy', '{}',
'["router bgp {asn}", "show ip bgp summary", "show ip bgp"]',
'["Using public ASN when private would suffice", "Not filtering routes at AS boundaries"]'
FROM topics t WHERE t.slug = 'autonomous-systems' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 12. IPv6
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3 — Network', ARRAY['RFC 8200', 'RFC 4861 (NDP)'],
E'## What Is IPv6?\n\n**IPv6** is the successor to IPv4, expanding the address space from 32 bits (4.3 billion addresses) to **128 bits** (340 undecillion addresses). IPv6 also simplifies the header, eliminates NAT for most use cases, and mandates IPsec support.\n\n## Address Format\n\n```\n2001:0DB8:0000:0001:0000:0000:0000:0001\n2001:DB8:0:1::1      (compressed)\nPrefix: 2001:DB8:0:1::/64\n```\n\n## Address Types\n\n| Type | Prefix | Purpose |\n|------|--------|---------|\n| Global Unicast | 2000::/3 | Public routable |\n| Link-Local | FE80::/10 | Same-link only (auto-configured) |\n| Unique Local | FC00::/7 | Private (like RFC 1918) |\n| Multicast | FF00::/8 | One-to-many |\n| Loopback | ::1 | Localhost |\n\n## NDP (Neighbor Discovery Protocol)\n\nReplaces ARP in IPv6:\n- **Router Solicitation/Advertisement**: Discover routers and prefixes\n- **Neighbor Solicitation/Advertisement**: Resolve IPv6 → MAC\n- **SLAAC**: Stateless Address Auto-Configuration using RA prefix + EUI-64',
E'## Essential Commands\n\n```\n! Enable IPv6 routing\nRouter(config)# ipv6 unicast-routing\n\n! Configure address\nRouter(config-if)# ipv6 address 2001:DB8:1::1/64\nRouter(config-if)# ipv6 address FE80::1 link-local\n\n! Enable OSPFv3\nRouter(config)# ipv6 router ospf 1\nRouter(config-if)# ipv6 ospf 1 area 0\n\n! Verify\nRouter# show ipv6 interface brief\nRouter# show ipv6 neighbors\nRouter# show ipv6 route\n```',
'address-format', '{}',
'["ipv6 unicast-routing", "ipv6 address {addr}/{prefix}", "show ipv6 interface brief", "show ipv6 route", "show ipv6 neighbors"]',
'["Forgetting ipv6 unicast-routing globally", "Not understanding link-local scope", "EUI-64 exposing MAC addresses (privacy concern)"]'
FROM topics t WHERE t.slug = 'ipv6' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 13. Remote Access
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3–7', ARRAY['RFC 4301 (IPsec)', 'RFC 7296 (IKEv2)'],
E'## Remote Access Technologies\n\n**Remote access** allows users outside the corporate network to securely connect to internal resources. Key technologies:\n\n- **IPsec VPN**: Full tunnel, encrypts all traffic, requires client software\n- **SSL/TLS VPN**: Browser-based or lightweight client, works through firewalls\n- **DMVPN**: Dynamic multipoint VPN for hub-and-spoke WAN\n- **Site-to-Site VPN**: Permanent tunnel between two fixed locations\n\n## IPsec Phases\n\n**Phase 1 (ISAKMP/IKE)**: Negotiate encryption, authenticate peers, establish secure channel\n**Phase 2 (IPsec)**: Negotiate data encryption parameters, create Security Associations (SAs)\n\n## VPN Split Tunneling\n\n- **Full tunnel**: ALL traffic goes through VPN\n- **Split tunnel**: Only corporate traffic through VPN; internet goes direct',
E'## Essential Commands\n\n```\n! ISAKMP policy\nRouter(config)# crypto isakmp policy 10\nRouter(config-isakmp)# encryption aes 256\nRouter(config-isakmp)# hash sha256\nRouter(config-isakmp)# authentication pre-share\n\n! IPsec transform set\nRouter(config)# crypto ipsec transform-set MYSET esp-aes 256 esp-sha256-hmac\n\n! Crypto map\nRouter(config)# crypto map MYMAP 10 ipsec-isakmp\nRouter(config-crypto-map)# set peer 203.0.113.2\nRouter(config-crypto-map)# set transform-set MYSET\nRouter(config-crypto-map)# match address VPN-TRAFFIC\n\n! Verify\nRouter# show crypto isakmp sa\nRouter# show crypto ipsec sa\n```',
'vpn-tunnel', '{}',
'["crypto isakmp policy {id}", "crypto ipsec transform-set {name}", "crypto map {name}", "show crypto isakmp sa", "show crypto ipsec sa"]',
'["Mismatched ISAKMP policies between peers", "ACL for interesting traffic not matching both directions", "NAT translating VPN traffic (need NAT exemption)"]'
FROM topics t WHERE t.slug = 'remote-access' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 14. SSH
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 7 — Application', ARRAY['RFC 4253'],
E'## What Is SSH?\n\n**Secure Shell** provides encrypted remote management of network devices, replacing insecure **Telnet** (which sends everything in plaintext, including passwords).\n\n## SSH vs Telnet\n\n| Feature | Telnet | SSH |\n|---------|--------|-----|\n| Encryption | None | AES/ChaCha20 |\n| Authentication | Password only | Password, keys, certificates |\n| Port | TCP 23 | TCP 22 |\n| Security | Terrible | Strong |\n\n## SSH Versions\n\n- **SSHv1**: Deprecated, vulnerable to man-in-the-middle attacks\n- **SSHv2**: Current standard, supports key exchange, stronger algorithms\n\n## How SSH Works\n\n1. **Key Exchange**: Diffie-Hellman to establish shared secret\n2. **Server Authentication**: Server presents its RSA/ECDSA key\n3. **User Authentication**: Password or public key\n4. **Encrypted Channel**: All subsequent traffic is encrypted',
E'## Essential Commands\n\n```\n! Prerequisites\nRouter(config)# hostname R1\nRouter(config)# ip domain-name lab.local\n\n! Generate RSA keys\nRouter(config)# crypto key generate rsa modulus 2048\n\n! Create local user\nRouter(config)# username admin privilege 15 secret <STRONG-PASSWORD>\n\n! Configure VTY lines\nRouter(config)# line vty 0 4\nRouter(config-line)# transport input ssh\nRouter(config-line)# login local\nRouter(config-line)# exec-timeout 5 0\n\n! Force SSH version 2\nRouter(config)# ip ssh version 2\n\n! Verify\nRouter# show ip ssh\nRouter# show ssh\n```',
'auth-flow', '{}',
'["crypto key generate rsa modulus 2048", "ip ssh version 2", "transport input ssh", "login local", "show ip ssh"]',
'["Forgetting hostname and domain-name (required for RSA key generation)", "Leaving transport input as telnet ssh (should be ssh only)", "Using RSA key smaller than 2048 bits", "Not setting exec-timeout (sessions stay open forever)"]'
FROM topics t WHERE t.slug = 'ssh' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 15. ACLs
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3–4', ARRAY['RFC 3704 (BCP 38)'],
E'## What Are ACLs?\n\n**Access Control Lists** are ordered rules that **permit or deny** traffic based on criteria like source/destination IP, protocol, and port number. ACLs are fundamental to network security and traffic control.\n\n## ACL Types\n\n| Type | Number Range | Matches On |\n|------|-------------|------------|\n| Standard | 1–99, 1300–1999 | Source IP only |\n| Extended | 100–199, 2000–2699 | Source IP, dest IP, protocol, port |\n| Named | Text name | Flexible (standard or extended) |\n\n## Processing Rules\n\n1. ACLs are processed **top-down** — first match wins\n2. There is an **implicit deny any** at the end\n3. ACLs are applied **per-interface, per-direction** (in or out)\n4. One ACL per interface per direction per protocol\n\n## Direction Logic\n\n- **Inbound**: Filter packets arriving ON the interface\n- **Outbound**: Filter packets leaving THROUGH the interface',
E'## Essential Commands\n\n```\n! Named extended ACL\nRouter(config)# ip access-list extended DENY-TELNET\nRouter(config-ext-nacl)# deny tcp any any eq 23\nRouter(config-ext-nacl)# permit ip any any\n\n! Apply to interface\nRouter(config-if)# ip access-group DENY-TELNET in\n\n! Standard ACL\nRouter(config)# access-list 10 permit 10.0.1.0 0.0.0.255\n\n! Verify\nRouter# show access-lists\nRouter# show ip interface (shows applied ACLs)\n```\n\n## Best Practices\n\n- Place **extended ACLs close to the source**\n- Place **standard ACLs close to the destination**\n- Always end with an explicit `permit ip any any` if you want to allow other traffic\n- Use **named ACLs** for easier editing (can insert/delete lines)',
'rule-processing', '{}',
'["ip access-list extended {name}", "permit {proto} {src} {dst} eq {port}", "deny {proto} {src} {dst}", "ip access-group {name} in/out", "show access-lists"]',
'["Forgetting the implicit deny at the end", "Placing extended ACL far from source (inefficient)", "Applying ACL in the wrong direction (in vs out)", "Not including permit ip any any when needed"]'
FROM topics t WHERE t.slug = 'acls' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 16. NAT
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3 — Network', ARRAY['RFC 3022'],
E'## What Is NAT?\n\n**Network Address Translation** maps private (RFC 1918) IP addresses to public IP addresses, allowing internal hosts to access the internet. NAT also provides a degree of security by hiding internal addressing.\n\n## NAT Terminology\n\n| Term | Meaning |\n|------|---------|\n| Inside Local | Private IP on the internal network |\n| Inside Global | Public IP representing the internal host |\n| Outside Local | How the external host appears internally |\n| Outside Global | Real public IP of the external host |\n\n## NAT Types\n\n- **Static NAT**: Permanent 1:1 mapping (e.g., web server)\n- **Dynamic NAT**: Pool of public IPs, assigned on demand\n- **PAT (Overload)**: Many-to-one using port numbers',
E'## Essential Commands\n\n```\n! Define inside/outside\nRouter(config-if)# ip nat inside  (on LAN interface)\nRouter(config-if)# ip nat outside (on WAN interface)\n\n! Static NAT\nRouter(config)# ip nat inside source static 10.0.1.100 203.0.113.100\n\n! Dynamic NAT\nRouter(config)# ip nat pool MYPOOL 203.0.113.10 203.0.113.20 netmask 255.255.255.0\nRouter(config)# access-list 1 permit 10.0.1.0 0.0.0.255\nRouter(config)# ip nat inside source list 1 pool MYPOOL\n\n! Verify\nRouter# show ip nat translations\nRouter# show ip nat statistics\nRouter# clear ip nat translation *\n```',
'translation-table', '{}',
'["ip nat inside", "ip nat outside", "ip nat inside source static {local} {global}", "ip nat inside source list {acl} pool {name}", "show ip nat translations"]',
'["Forgetting to mark interfaces as inside/outside", "ACL not matching the correct source network", "NAT pool exhaustion (not enough public IPs)", "Not clearing NAT translations after config changes"]'
FROM topics t WHERE t.slug = 'nat' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 17. PAT
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3–4', ARRAY['RFC 3022'],
E'## What Is PAT?\n\n**Port Address Translation** (also called NAT Overload) maps multiple internal IP addresses to a **single public IP** by using unique **source port numbers** to distinguish sessions.\n\n## How PAT Works\n\n```\nInternal:  10.0.1.10:49152 → 8.8.8.8:53\nTranslated: 203.0.113.1:1024 → 8.8.8.8:53\n\nInternal:  10.0.1.11:49153 → 8.8.8.8:53\nTranslated: 203.0.113.1:1025 → 8.8.8.8:53\n```\n\nBoth hosts share 203.0.113.1, distinguished by source ports.\n\n## PAT vs NAT\n\n| Feature | Static/Dynamic NAT | PAT |\n|---------|-------------------|-----|\n| Mapping | 1:1 | Many:1 |\n| Public IPs needed | One per host | One total |\n| Port tracking | No | Yes |\n| Inbound connections | Yes (static) | No (requires port forwarding) |',
E'## Essential Commands\n\n```\n! PAT using interface IP\nRouter(config)# access-list 1 permit 10.0.1.0 0.0.0.255\nRouter(config)# ip nat inside source list 1 interface GigabitEthernet0/1 overload\n\n! Don''t forget inside/outside\nRouter(config-if)# ip nat inside\nRouter(config-if)# ip nat outside\n\n! Verify\nRouter# show ip nat translations\nRouter# show ip nat statistics\n```\n\nThe key difference from dynamic NAT is the **overload** keyword.',
'port-mapping', '{}',
'["ip nat inside source list {acl} interface {if} overload", "show ip nat translations", "show ip nat statistics"]',
'["Forgetting the overload keyword (without it, only one host can translate)", "ACL not matching all internal subnets", "Port exhaustion under very heavy load (65535 port limit per IP)"]'
FROM topics t WHERE t.slug = 'pat' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 18. Wireless APs
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 1–2', ARRAY['IEEE 802.11'],
E'## Wireless Access Points\n\nA **wireless access point (AP)** is a Layer 2 device that bridges wireless clients to the wired LAN. APs operate in the **2.4 GHz** and **5 GHz** bands (and now 6 GHz with Wi-Fi 6E).\n\n## Key Concepts\n\n- **SSID**: Network name broadcast by the AP\n- **BSSID**: AP''s MAC address for a specific SSID\n- **Channel**: Frequency slice the AP operates on\n- **802.11 Standards**: a/b/g/n/ac/ax (Wi-Fi 4/5/6)\n\n## 2.4 GHz Channels\n\nOnly channels **1, 6, and 11** are non-overlapping. Using any other channel causes **co-channel interference** with neighbors.\n\n## AP Modes\n\n- **Autonomous**: Self-managed, standalone configuration\n- **Lightweight (LWAP)**: Managed by a Wireless LAN Controller (WLC)\n- **FlexConnect**: WLC-managed but can switch traffic locally',
E'## Deployment Tips\n\n- Use **non-overlapping channels** (1/6/11 for 2.4 GHz)\n- Set **transmit power** to minimize overlap between APs\n- Mount APs **ceiling height, facing down**\n- Plan for **20-25 clients per AP** in enterprise environments\n- Use **5 GHz** for high-density areas (more non-overlapping channels)\n\n## Commands (Autonomous AP)\n\n```\nAP(config)# dot11 ssid CorpWiFi\nAP(config-ssid)# authentication open\nAP(config-ssid)# authentication key-management wpa version 2\nAP(config-ssid)# wpa-psk ascii MySecretKey\n```',
'channel-plan', '{}',
'["dot11 ssid {name}", "authentication open", "channel {num}", "power local {level}"]',
'["Using overlapping channels (e.g., 1 and 3)", "Too many APs at high power (increases interference)", "Not separating management and client VLANs", "Placing APs in closets or corners instead of open ceilings"]'
FROM topics t WHERE t.slug = 'wireless-ap' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 19. Wireless Controllers
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 2–3', ARRAY['RFC 5415 (CAPWAP)'],
E'## Wireless LAN Controllers\n\nA **WLC** centrally manages multiple lightweight access points (LWAPs). Instead of configuring each AP individually, you configure the WLC once and it pushes settings to all APs.\n\n## CAPWAP Protocol\n\n**Control And Provisioning of Wireless Access Points** (UDP 5246/5247):\n- **Control channel**: Encrypted management traffic\n- **Data channel**: Client traffic (can be tunneled to WLC or locally switched)\n\n## WLC Functions\n\n- AP discovery and registration\n- WLAN/SSID management\n- Security policy enforcement\n- Roaming coordination\n- RF management (channel, power)\n- Client load balancing',
E'## Deployment Architecture\n\n- **Centralized**: All traffic tunnels through WLC (control + data)\n- **FlexConnect**: Control through WLC, data switched locally at AP\n- **Cloud-managed**: Meraki/Mist — WLC function in the cloud\n\n## Key Concepts\n\n```\n! WLC WLAN creation\nwlan CorpWiFi 1 CorpWiFi\n  security wpa wpa2\n  security wpa akm dot1x\n  no shutdown\n\n! Map WLAN to VLAN\ninterface vlan 10\n```\n\n## AP Join Process\n\n1. AP boots, gets IP via DHCP\n2. AP discovers WLC (DHCP option 43, DNS, broadcast)\n3. CAPWAP tunnel established\n4. AP downloads config and firmware\n5. AP begins broadcasting SSIDs',
'capwap', '{}',
'["wlan {name} {id} {ssid}", "security wpa wpa2", "no shutdown", "show ap summary"]',
'["DHCP Option 43 not configured for AP discovery", "Firmware mismatch between AP and WLC", "Not enough AP licenses on the WLC", "CAPWAP ports blocked by firewall"]'
FROM topics t WHERE t.slug = 'wireless-controller' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 20. Wireless Security
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 2', ARRAY['IEEE 802.11i', 'IEEE 802.1X'],
E'## Wireless Security\n\n### Evolution of Wi-Fi Security\n\n| Protocol | Year | Encryption | Status |\n|----------|------|-----------|--------|\n| WEP | 1997 | RC4 | **Broken** — cracked in minutes |\n| WPA | 2003 | TKIP | Deprecated |\n| WPA2 | 2004 | AES-CCMP | Current standard |\n| WPA3 | 2018 | AES-GCMP / SAE | Recommended |\n\n### Authentication Modes\n\n- **Personal (PSK)**: Pre-shared key — all users share one password\n- **Enterprise (802.1X)**: Per-user authentication via RADIUS server\n\n### 802.1X Components\n\n- **Supplicant**: Client device\n- **Authenticator**: AP or WLC\n- **Authentication Server**: RADIUS (FreeRADIUS, ISE, NPS)\n\n### Wireless Threats\n\n- **Rogue APs**: Unauthorized APs on the network\n- **Evil Twin**: Fake AP mimicking a legitimate SSID\n- **Deauthentication attacks**: Spoofed deauth frames (mitigated by PMF/802.11w)\n- **KRACK**: Key reinstallation attack on WPA2 (patched)',
E'## Best Practices\n\n1. Use **WPA3-Enterprise** (or WPA2-Enterprise minimum)\n2. Enable **PMF (802.11w)** to protect management frames\n3. Deploy **802.1X with RADIUS** for per-user credentials\n4. Enable **rogue AP detection** on the WLC\n5. Use **strong PSK** if Enterprise isn''t feasible (20+ characters)\n6. Disable **WPS** (Wi-Fi Protected Setup) — vulnerable to brute force\n\n## Commands\n\n```\n! WPA3-Enterprise on WLC\nwlan SecureWiFi 1 SecureWiFi\n  security wpa3\n  security dot1x\n  security pmf required\n\n! RADIUS server\nradius server ISE\n  address ipv4 10.0.1.200 auth-port 1812\n  key MyRADIUSSecret\n```',
'auth-flow', '{}',
'["security wpa3", "security dot1x", "security pmf required", "radius server {name}", "address ipv4 {ip}"]',
'["Still using WPA2-Personal in enterprise environments", "Not enabling PMF (allows deauth attacks)", "Weak PSK (under 12 characters)", "Not deploying rogue AP detection"]'
FROM topics t WHERE t.slug = 'wireless-security' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 21. Wireless Topology
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 1–2', ARRAY['IEEE 802.11'],
E'## Wireless Network Design\n\nDesigning a wireless network requires balancing **coverage**, **capacity**, and **interference**.\n\n## Site Survey Types\n\n- **Predictive**: Software-based planning using floor plans\n- **Passive**: Walk the site with a survey tool, measuring existing RF\n- **Active**: Connect to APs and measure real throughput\n\n## Design Considerations\n\n- **Coverage area**: Each AP covers roughly 2,500–3,500 sq ft\n- **Client density**: 20-25 clients per AP in typical office\n- **Channel planning**: Non-overlapping channels (1/6/11 for 2.4 GHz)\n- **AP placement**: Ceiling-mounted, avoid metal obstructions\n- **Roaming**: Overlap between APs for seamless handoff\n\n## Deployment Models\n\n- **Autonomous**: Each AP managed individually\n- **Controller-based**: Centralized WLC management\n- **Cloud-managed**: Meraki, Mist — management from the cloud\n- **Mesh**: APs wirelessly backhaul to each other',
E'## Design Rules of Thumb\n\n1. **20% overlap** between adjacent APs for roaming\n2. **Channel plan first** — then adjust power to match\n3. **5 GHz preferred** for high-density (more channels available)\n4. **Separate SSIDs** for corporate, guest, IoT\n5. **Band steering**: Push dual-band clients to 5 GHz\n\n## Channel Planning\n\n```\n2.4 GHz: Channels 1, 6, 11 (non-overlapping)\n5 GHz:   Channels 36-48, 52-64, 100-144, 149-165\n         (UNII-1, UNII-2, UNII-2e, UNII-3)\n6 GHz:   Channels 1-233 (Wi-Fi 6E) — 59 non-overlapping 20 MHz channels\n```',
'site-plan', '{}',
'["channel {num}", "power local {level}", "dot11 ssid {name}"]',
'["All APs on the same channel", "APs at max power causing interference", "Not accounting for wall attenuation", "Skipping a proper site survey"]'
FROM topics t WHERE t.slug = 'wireless-topology' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);

-- 22. Firewalls
INSERT INTO topic_content (topic_id, osi_layer, rfc_references, theory_md, practical_md, diagram_type, diagram_data, key_commands, common_mistakes)
SELECT t.id, 'Layer 3–7', ARRAY['RFC 2979'],
E'## What Is a Firewall?\n\nA firewall controls traffic between network segments by enforcing **security policies**. Modern firewalls are **stateful** — they track connection state and allow return traffic automatically.\n\n## Firewall Types\n\n| Type | Inspects | Example |\n|------|----------|--------|\n| Packet filter | IP/port headers | Router ACLs |\n| Stateful | Connection state | Cisco ASA, iptables |\n| Application (NGFW) | L7 content | Palo Alto, Firepower |\n| WAF | HTTP requests | CloudFlare, F5 |\n\n## Zone-Based Firewall (ZBF)\n\nCisco IOS zone-based firewalls group interfaces into **security zones**:\n\n- **INSIDE**: Trusted internal network\n- **OUTSIDE**: Untrusted internet\n- **DMZ**: Semi-trusted servers (web, mail)\n\n**Zone pairs** define allowed traffic directions:\n- INSIDE → OUTSIDE: Allow and inspect\n- OUTSIDE → INSIDE: Deny (except return traffic)\n- INSIDE → DMZ: Allow specific ports\n\n## Stateful Inspection\n\nThe firewall maintains a **state table** tracking every active connection. Return traffic matching an existing session is automatically permitted — no explicit rule needed.',
E'## Essential Commands (IOS ZBF)\n\n```\n! Create zones\nRouter(config)# zone security INSIDE\nRouter(config)# zone security OUTSIDE\n\n! Assign interfaces to zones\nRouter(config-if)# zone-member security INSIDE\nRouter(config-if)# zone-member security OUTSIDE\n\n! Class-map to match traffic\nRouter(config)# class-map type inspect match-any ALLOWED\nRouter(config-cmap)# match protocol http\nRouter(config-cmap)# match protocol https\nRouter(config-cmap)# match protocol dns\n\n! Policy-map to define action\nRouter(config)# policy-map type inspect INSIDE-OUT\nRouter(config-pmap)# class type inspect ALLOWED\nRouter(config-pmap-c)# inspect\n\n! Zone pair\nRouter(config)# zone-pair security IN-OUT source INSIDE destination OUTSIDE\nRouter(config-sec-zone-pair)# service-policy type inspect INSIDE-OUT\n\n! Verify\nRouter# show zone security\nRouter# show zone-pair security\nRouter# show policy-map type inspect\n```',
'zone-diagram', '{}',
'["zone security {name}", "zone-member security {name}", "zone-pair security {name} source {z1} destination {z2}", "class-map type inspect", "policy-map type inspect", "service-policy type inspect"]',
'["Forgetting that traffic between zones is denied by default", "Not creating zone pairs for both directions when needed", "Blocking return traffic by not using inspect", "Assigning an interface to a zone breaks existing connectivity until policies are applied"]'
FROM topics t WHERE t.slug = 'firewalls' AND NOT EXISTS (SELECT 1 FROM topic_content tc WHERE tc.topic_id = t.id);
